Feat/stake gateway2.5 updates
bobanetwork/boba_legacy pull request #1006
Opened 2023-07-03 14:31 UTC by alvaro-ricotta

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

This committee was sent to a new branch to avoid inconveniences:

## Changes

DAO:
Most of the components belonging to the DAO page have been refactored.

1. The MODAL component has been completely updated.
2. New component: LinearProgress.
3. New states for proposals.
4. Button updates.
5. New design for Lightbox in Create Proposal.
6. New design for Lightbox Vote.
7. Complete refactoring of DelegateBoba and Delegate xBoba.
8. Code refactoring and creation of Label component
9. New preloader component for loading proposals

GENERAL:

1. The Button component has been updated to have an option without background.
2. New component: TabContent (Storybook and testing implementation pending).
3. New component: TabHeader (Storybook and testing implementation pending).
4. The main theme has been updated with new colors for the lightbox backgrounds.
5. New view for the Connect modal.
6. The Dropdown component has been updated to display errors when the "error" property is defined, which is ideal for validating submissions where options have not been selected.

2023-07-06 23:09 UTC, jemeza requested changes
Code is looking good, could you look at some of the comments?

2023-07-06 23:09 UTC, jemeza commented on packages/boba/gateway/src/containers/modals/dao/old/NewProposalModalOldDao.js
> -          >
This dropdown could be a bit cleaner. The top two edges are sharp and visible.
![Screenshot 2023-07-06 at 4 52 54 PM](https://github.com/bobanetwork/boba/assets/57341979/d3da13bb-b8ef-4582-8eb5-87f47b6c7196)
 I think you can raise the body that holds the options or lower it and round the top corners.

2023-07-06 23:09 UTC, jemeza commented on packages/boba/gateway/src/containers/modals/dao/old/NewProposalModalOldDao.js
> -          >
It also let's me create a proposal and submit even before I have connected my wallet and even if I don't have the required amount of boba.

2023-07-06 23:09 UTC, jemeza commented on packages/boba/gateway/src/components/global/modalTypography/index.tsx
> +export const ModalTypography = styled(Typography)`
Would it be better to add a` themes.ts` file to `components/global/typography` with these styles instead of making a new component?

2023-07-06 23:09 UTC, jemeza commented on packages/boba/gateway/src/containers/dao/OldDao.js
> +  const handleNewProposal = () => {
I think there may be an error in how the votes are handled or potentially in what the proposal  threshold is set to.

2023-07-09 07:15 UTC, sk-enya commented on packages/boba/gateway/src/containers/modals/dao/old/NewProposalModalOldDao.js
> -          >
Good catch, 
1/ for dropdown my changes of Select WIll fix this once sync with develop
2/ @alvaro-ricotta please make sure to test the corner.

2023-07-09 07:18 UTC, sk-enya commented
@alvaro-ricotta please fix the conflict on top priority!

2023-07-09 07:20 UTC, sk-enya commented on packages/boba/gateway/src/images/close.svg:Zone.Identifier
What is this file for?

2023-07-09 07:20 UTC, sk-enya commented on packages/boba/gateway/src/images/icons/arrowdown.svg:Zone.Identifier
What is the use of this file. please remove if it's of now use!

2023-07-10 13:02 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/global/modalTypography/index.tsx
> +export const ModalTypography = styled(Typography)`
100% i´ll transform this into a theme

2023-07-10 13:02 UTC, alvaro-ricotta commented
> @alvaro-ricotta please fix the conflict on top priority!

fixed

2023-07-10 13:02 UTC, alvaro-ricotta commented on packages/boba/gateway/src/images/close.svg:Zone.Identifier
this cache file, i´ll remove it.

2023-07-10 13:03 UTC, alvaro-ricotta commented on packages/boba/gateway/src/images/icons/arrowdown.svg:Zone.Identifier
same as previeus, cache file.

2023-07-10 13:03 UTC, alvaro-ricotta commented on packages/boba/gateway/src/containers/dao/OldDao.js
> +  const handleNewProposal = () => {
This is comming from original code, we don´t want to migrate the functionality during this design updates

2023-07-12 04:16 UTC, sk-enya approved these changes
Looks good, we will fix the comments in next updates.

2023-07-12 04:52 UTC, merged