[WIP] Jemeza/gtwy 2.5 history
bobanetwork/boba_legacy pull request #1007
Opened 2023-07-03 15:58 UTC by jemeza

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

This PR updates the history page for gateway 2.0

## Changes

Refactored Dropdown Component to include two types of components
Added `to` and `from` to the network

## Testing

WIP

2023-07-20 12:56 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/global/svg/index.tsx
> +export const Svg: React.FC<SvgTypes> = ({ src, className, fill, alt }) => (
If you changed the props of a component, make sure to update the changes in Storybook, and if it has/comes with tests, ensure to add the test cases.

2023-07-20 12:58 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/global/svg/types.ts
> +  alt?: string
ALT is not a valid attribute in an SVG. If you want, you can use a hidden TITLE for SEO purposes. However, it's important to note that our dapp does not have server-side rendering, so it's not required.

2023-07-20 13:01 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/global/table/styles.ts
> +  @media (max-width: 960px) {
We are going to need responsive tags throughout the app. Are you up for creating a hook? This way, the implementation would look similar to:

${mobile} {
...code
}

${tablet} {
...code
}

and we avoid defining different queries throughout each styled component.

2023-07-20 13:04 UTC, alvaro-ricotta commented on packages/boba/gateway/src/containers/history/History.js
> +                theme.palette.mode === 'light'
Do not use ternaries in the code, and avoid using inline styles. Please move this code to a styled component.

2023-07-21 12:10 UTC, sk-enya commented on packages/boba/gateway/src/components/global/table/styles.ts
> +  @media (max-width: 960px) {
Yeah, that's a good point that must be needed. @jemeza can you please prepare the same kind of structure and get it added.

2023-07-21 12:29 UTC, sk-enya requested changes

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/util/objectManipulation.ts
> +}
Are you sure this is the way to validate the wether it's Array or not?

Better to make use of. [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray)

```
Array.isArray(inputArray)
```

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/selectors/transactionSelector.js
> +  return validArray(Object.values(state.transaction))
It's good to move this validation at the places where we are using this state value instead of adding logics in the selectors itself.
Let's refactored this make selectors are just for selecting the value out of state.

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/containers/history/History.styles.js
>  import styled from '@emotion/styled'
Please refactored this styles.js with `styles.ts` import the styled from `styled-components` so we can make use of our theme here.

Please rewrite whole file and it's import in history.js

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/containers/history/History.styles.js
>  import { Box } from '@mui/material'
Let's remove use of `Box` from material UI prepare styles with div.

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/containers/history/History.styles.js
> +export const Table = styled(Box)(({ theme }) => ({
Let's move this to styles.ts and `import styled from styled-components` and please do not make use of Box from material UIl.

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/containers/history/History.js
>  import styles from './TX_All.module.scss'
Let's remove use of module.scss and move all the styles with styled component so we can use the theme correctly .

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/containers/history/constants.ts
> +export const ALL_NETWORKS = {
Please add types / interface to this constants and below others.

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/components/filter/index.tsx
> +  }, [defaultItem])
Is `defaultItem` also getting changed from parent? if not I don't think this hook is required.

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/components/filter/index.tsx
> +        }
Let's move this code style.ts itself.

```
export const Header = styled.div.attrs<{ error: boolean, className, isOpen }>({
  className: `dropdown ${className} ${isOpen ? 'active' : ''}`
})``

```

2023-07-21 12:29 UTC, sk-enya commented on packages/boba/gateway/src/components/filter/index.tsx
> +                }
You can also move this className down to styles.ts  files with logic mention above so it will be much cleaner.

2023-07-21 14:18 UTC, jemeza commented on packages/boba/gateway/src/components/filter/index.tsx
> +        }
that's super cool, will do

2023-07-26 09:42 UTC, jemeza commented on packages/boba/gateway/src/util/objectManipulation.ts
> +}
it wasn't checking wether it was valid array or not but rather extracting valid values

2023-07-26 09:42 UTC, jemeza commented on packages/boba/gateway/src/util/objectManipulation.ts
> +}
i did move the logic

2023-08-01 06:11 UTC, sk-enya approved these changes
Looks good!

2023-08-01 07:05 UTC, merged