V2 earn stake
bobanetwork/boba_legacy pull request #1056
Opened 2023-07-24 14:41 UTC by alvaro-ricotta

## Overview

1. Stake logic moved to StakeModal
2. PlaceholderConnect component has been created. 
3. New layout and design for Stake
4. All files has been migrated to ts + styled-components

Screenshots : 

![image](https://github.com/bobanetwork/boba/assets/81116391/78d681e6-fc72-4152-8c60-008857ab6f13)
![image](https://github.com/bobanetwork/boba/assets/81116391/d9cf8e0f-59c0-4ec5-8961-1888e6625d7d)
![image](https://github.com/bobanetwork/boba/assets/81116391/ed25cfd3-944d-414b-988d-a8ba2adf610b)

2023-07-25 07:21 UTC, sk-enya requested changes

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/layout/Header/__snapshots__/index.test.tsx.snap
> -        class="sc-kuWgmH gPrhcx"
Please check once this should not have to be change as far as the change in class names.

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/modal/Modal.tsx
>  import * as S from './styles'
Does it take too much time to convert these styles to `styles.ts` with `styled-component`?

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/modal/Modal.tsx
> +          <S.Style transparent={!!transparent || !!isMobile}>
Seems like you are using the wrong variable name it should say `isMobileDevice`

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/modal/Modal.tsx
> +  const isMobileDevice = useMediaQuery(theme.breakpoints.down('md'))
Do you it's better to handle it via styles.ts instead of loading from material

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/modal/types.ts
> +  onClose: any
Should say function instead of any.

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
This folder name is supposed to say `StakeList` instead of `transactionList` as it's more about stake not history page txs

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
> +  const [state, setState] = useState({
Can you please give better name instead of state as it might be confusing longer run with redux/state.

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
> +export default connect(mapStateToProps)(TransactionList)
Why do we have connect here?
We can directly read the state from the redux store using `useSelector`. and even it looks like you missed remove this code as `props.fixed` is not getting used anywhere in the file.

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/components/stake/transactionList/types.ts
> +type TransactionType = {
should rename to `StakeType` & `IStakeTypeList`.

2023-07-25 07:21 UTC, sk-enya commented on packages/boba/gateway/src/containers/modals/stake/DepositStake.tsx
> +export default connect(mapStateToProps)(DepositStake)
Why do we need to use this?
Can't we use directly the useSelector to get the value of all states from redux? as it's functional component.

2023-07-25 09:19 UTC, sk-enya commented
In design snapshot share above it seems `Stake Button` needs to be full width.

2023-07-25 22:56 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/modal/Modal.tsx
> +          <S.Style transparent={!!transparent || !!isMobile}>
Don´t worry about it i´ll refactory all entire mobile-/table styles to styledcomponents

2023-07-25 22:58 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
For that same reason, there is the Stake folder; if I'm referring to TransactionList inside Stake, I'm talking about the StakeTransactionList, but if you prefer, I can rename it.

2023-07-25 23:07 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
> +  const [state, setState] = useState({
Done

2023-07-25 23:07 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
> +export default connect(mapStateToProps)(TransactionList)
Done

2023-07-25 23:08 UTC, alvaro-ricotta commented on packages/boba/gateway/src/containers/modals/stake/DepositStake.tsx
> +export default connect(mapStateToProps)(DepositStake)
Done

2023-07-25 23:41 UTC, sk-enya commented on packages/boba/gateway/src/components/stake/transactionList/index.tsx
yeah, can you please rename it? will help us to cleanup the code base and reduce confusion in future.

2023-07-25 23:45 UTC, sk-enya commented on packages/boba/gateway/src/components/modal/Modal.tsx
> +          <S.Style transparent={!!transparent || !!isMobile}>
It's more about the variable name not about the refactoring, please read the variable name `isMobile` which is not defined above.

2023-08-01 04:05 UTC, sk-enya approved these changes

2023-08-01 05:51 UTC, merged