[DRAFT] Gateway: Teleportation integration
bobanetwork/boba_legacy pull request #1083
Opened 2023-08-05 10:34 UTC by wsdt

Closes #1034

2023-08-23 23:10 UTC, Boyuan-Chen reviewed
It seems that the gateway doesn't work. 
```
NS: ERROR: InitializeBase  Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
```

2023-08-23 23:10 UTC, boyuan-chen commented on package-lock.json
Can we remove this file? Since we use `yarn` to the package management.

2023-08-23 23:10 UTC, boyuan-chen commented on packages/boba/contracts/teleportation_deploy_logs/.gitkeep
Can we delete this empty file?

2023-08-23 23:10 UTC, Boyuan-Chen commented on packages/boba/subgraph/L2/config/local.json
What's this used for?

2023-08-23 23:10 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/utils/chains.ts
> +    url: 'https://ethereum-goerli.publicnode.com', //'https://goerli.gateway.tenderly.co',
Why don't use our tenderly RPC endpoint?

2023-08-23 23:12 UTC, Boyuan-Chen commented
The integration tests need to be fixed.

2023-08-24 08:48 UTC, souradeep-das commented
not sure if this is the right place, can we somehow alert a user and let them know - that they should not use an unconventional wallet/multisig (if they are using a contract account as recipient) with a costly fallback method. (since we pass 3000 gas for disbursements

2023-08-25 11:13 UTC, wsdt commented on packages/boba/subgraph/L2/config/local.json
For testnet deployments & a local graph-node to debug on networks that are not supported.

2023-08-25 11:14 UTC, wsdt commented on packages/boba/contracts/teleportation_deploy_logs/.gitkeep
I'm logging the Teleportation routes there (to have a file that logs them). Especially for mainnet deployment then. Otherwise this would need to be read on-chain.

2023-08-25 13:41 UTC, wsdt commented
> It seems that the gateway doesn't work.
> 
> ```
> NS: ERROR: InitializeBase  Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
> ```

If I check out the current branch it works. I guess this is because the @boba/register package has not been rebuilt? 

In the PR I had to change the addresses from `Proxy__Teleportation` to `Proxy_L2Teleportation` etc. 

"Proxy__L1Teleportation": "0x7f6a32bCaA70c65E08F2f221737612F6fC18347A",
  "Proxy__L2Teleportation": "0xf4d179d3a083Fa3Eede935FaF4C679D32d514186",
  "L1Teleportation": "0xD151c8F0dc69618e6180a2dC74B05cCE3E08e0aC",
  "L2Teleportation": "0x46FA6144C61d2bb9aCDc3Ca90C8673dd9B6caEB2"

2023-08-25 17:32 UTC, wsdt commented
> The integration tests need to be fixed.

fixed thx!

2023-08-25 18:41 UTC, wsdt commented
> It seems that the gateway doesn't work.
> 
> ```
> NS: ERROR: InitializeBase  Error: invalid contract address or ENS name (argument="addressOrName", value=undefined, code=INVALID_ARGUMENT, version=contracts/5.7.0)
> ```

was a mainnet issue, since Teleportation is not deployed there yet. Fixed good catch!

2023-08-25 18:52 UTC, wsdt commented
@souradeep-das 
![image](https://github.com/bobanetwork/boba/assets/28724551/cc120290-2200-46ed-893a-b056c79ae175)

2023-08-29 00:33 UTC, Boyuan-Chen commented
I found another bug of gateway. It didn't work on my end and I got: 
```
NS: ERROR: InitializeBase  TypeError: Cannot read properties of undefined (reading 'payloadForL1SecurityFee')
```
Is this bug from the develop branch?

2023-08-29 20:11 UTC, wsdt commented
> payloadForL1SecurityFee

Just checked, I don't get that issue. 

And the code line that probably causes this is: 

**NetworkService.js:**
```js

 const networkDetail = getNetworkDetail({
      network,
      networkType
    })

if (NETWORK[network]) {
        this.payloadForL1SecurityFee = networkDetail.payloadForL1SecurityFee

```

Because networkDetail might be undefined for you for whatever reason? Just my guess. 

The `getNetworkDetail` function has not changed since March 2023 as well. 

Is the issue deterministic and still there? 

Thank you!

2023-08-29 22:10 UTC, Boyuan-Chen commented
> > payloadForL1SecurityFee
> 
> Just checked, I don't get that issue.
> 
> And the code line that probably causes this is:
> 
> **NetworkService.js:**
> 
> ```js
>  const networkDetail = getNetworkDetail({
>       network,
>       networkType
>     })
> 
> if (NETWORK[network]) {
>         this.payloadForL1SecurityFee = networkDetail.payloadForL1SecurityFee
> ```
> 
> Because networkDetail might be undefined for you for whatever reason? Just my guess.
> 
> The `getNetworkDetail` function has not changed since March 2023 as well. So yes the code that may cause this, should also be in develop if I didn't overlook something.
> 
> Is the issue deterministic and still there?
> 
> Thank you!

Ok! That's fine. Thank you.

2023-08-29 22:10 UTC, Boyuan-Chen approved these changes

2023-08-31 13:16 UTC, alvaro-ricotta commented
hey @wsdt quick question for you : 

![image](https://github.com/bobanetwork/boba/assets/81116391/3c26fc6d-6133-4c82-afbb-08be046c07b8)

I'm getting 2 different alerts: 
1) This bridge doesn't support smart-contract wallets that use a costly fallback method.
2) For this asset you need to bridge at least 0.001.

In the case of the second alert, it shouldn't be displayed by default, only when we input a value into the input.

On the other hand, I don't understand what the first alert refers to; I'm using a standard wallet.

![image](https://github.com/bobanetwork/boba/assets/81116391/a649db70-8395-490e-911a-c09d8eae0573)

After clicking on the bridge, which technically takes less than 1 minute (according to the time estimate), it asks me to wait for 64 blocks to confirm. Is this correct? Or should we update the text in case the bridge comes from now? The idea of using teleport is, I assume, to avoid waiting for 64 network confirmations, right?

In a general sense, the experience is incredible. The only detail I want to add is that I tried to bridge USDC on Goerli, and it tells me that the token is not currently supported.


The last detail is that it's not bidirectional. If we don't support assets bidirectionally, we shouldn't display the "now" option for certain assets/networks, right? For example, I can bridge from Goerli to Boba Goerli, but I can't bridge from Boba Goerli to Goerli.

2023-08-31 13:18 UTC, alvaro-ricotta commented
@jemeza after using now bridge history has been crashed 
![image](https://github.com/bobanetwork/boba/assets/81116391/27bb53e0-f79c-4be1-ab53-d123cc3bfb17)

2023-08-31 13:19 UTC, alvaro-ricotta commented
@wsdt keep in mind that your branch is out-of-date too =)

2023-08-31 13:20 UTC, alvaro-ricotta approved these changes

2023-08-31 13:55 UTC, sk-enya commented on packages/boba/gateway/src/services/networkService.js
> +
Good to remove this if we are not using.

2023-08-31 14:06 UTC, sk-enya commented on packages/boba/gateway/src/hooks/useBridge.ts
> +    return dispatch(
@wsdt  Correct me if I am wrong, we are going to add teleportation only for TESTNET?

It seems we have completely removed support for FAST LP bridging for MAINNET, is that correct or we still have to support the LP fast bridging on mainnet?

2023-08-31 14:15 UTC, sk-enya commented
@wsdt Is teleportation depends on bobaFeeContract? which is a relayer fee I guess we are not going to use right?

if not, remove this fee from the fee section at the bottom of the bridging container. `xChain Relay Fee - 10.0 BOBA` Also boba balance in MM and Wallet should be the same.
![Screenshot 2023-08-31 at 7 42 24 PM](https://github.com/bobanetwork/boba/assets/86316370/1cd8126f-757f-4735-876e-12ccecdb55c8)

2023-08-31 14:17 UTC, sk-enya commented
Values on fee sections needs to be added even selected teleportation it's showing the values of `L1LpContract / L2LpContract`
![Screenshot 2023-08-31 at 7 46 49 PM](https://github.com/bobanetwork/boba/assets/86316370/42a103cd-2ac8-4156-b84e-11536029bbdc)

2023-08-31 14:18 UTC, sk-enya commented
Looks like fast bridging is not working, failing with error.
![Screenshot 2023-08-31 at 7 39 59 PM](https://github.com/bobanetwork/boba/assets/86316370/b4317274-0d44-48c6-8254-07105bfc8444)
![Screenshot 2023-08-31 at 7 40 08 PM](https://github.com/bobanetwork/boba/assets/86316370/c9bbaf41-c89b-4a35-b4c0-2658a8212c97)

2023-08-31 14:20 UTC, sk-enya requested changes

2023-08-31 14:20 UTC, sk-enya commented on packages/boba/gateway/src/hooks/useBridge.ts
>        }
Better to support the fast bridging on Mainnet we should just extend this function to use the triggerTeleportAsset. like
```
if(BRIDGE_TYPE.TELEPORTATION) {
   receipt = await triggerTeleportAsset(amountWei, destChainIdBridge!)
}
```

2023-08-31 14:36 UTC, sk-enya commented
@wsdt I tried teleport bridge what I notice 

1. I am unable see transactions on history page as success dialog says. here is link to txs. https://testnet.bobascan.com/tx/0x6883b2edb41fbce96fc8eaad675eccc3befb133b853791dfb9bc6f22ae4dffd9
2. Still waiting to receive funds on my eth L1 goerli form boba L2  https://goerli.etherscan.io/address/0x81654daa2e297a140ca01f12367a4d9c9fc2bf51
3. As @alvaro-ricotta mentioned above dialog teleportation uses the same fast bridge dialog.

2023-08-31 14:38 UTC, sk-enya commented
Overall code looks good :) thanks!

2023-08-31 16:48 UTC, wsdt commented on packages/boba/gateway/src/hooks/useBridge.ts
> +    return dispatch(
yes as discussed, teleportation is only available on testnet in the first release.

2023-08-31 18:46 UTC, wsdt commented
@alvaro-ricotta 
Thanks for your feedback: 

1. the info message has been added as per prior feedback, please refer above's messages. There is no really reliable way of showing this info as we don't know if the user has a costly fallback method (if they have a smart wallet) on the destination chain. All we could do is checking if the destination address is a contract or not. 

2. Other UI remarks have been incorporated, thanks!

3. Teleportation is bi-directional, and yes USDC is not supported for now, that's why we show this message. Only BOBA and mostly ETH are supported at the moment.

2023-08-31 20:48 UTC, wsdt commented
> @wsdt I tried teleport bridge what I notice
> 
> 1. I am unable see transactions on history page as success dialog says. here is link to txs. https://testnet.bobascan.com/tx/0x6883b2edb41fbce96fc8eaad675eccc3befb133b853791dfb9bc6f22ae4dffd9
> 2. Still waiting to receive funds on my eth L1 goerli form boba L2  https://goerli.etherscan.io/address/0x81654daa2e297a140ca01f12367a4d9c9fc2bf51
> 3. As @alvaro-ricotta mentioned above dialog teleportation uses the same fast bridge dialog.

![image](https://github.com/bobanetwork/boba/assets/28724551/52cefe09-1da9-4325-9d6b-97f33b547f76)

2023-09-05 14:43 UTC, sk-enya approved these changes
@wsdt  all looks good!!

2023-09-05 15:16 UTC, sk-enya commented
looks failing with solidity coverage plugin @wsdt ,
https://github.com/bobanetwork/boba/actions/runs/6086249174/job/16512166025?pr=1083#step:9:1042

2023-09-06 07:30 UTC, wsdt commented
> looks failing with solidity coverage plugin @wsdt , https://github.com/bobanetwork/boba/actions/runs/6086249174/job/16512166025?pr=1083#step:9:1042

no was just a timeout from Account Abstraction

2023-09-06 07:30 UTC, merged