fixing issue on Avalanche Icons
bobanetwork/boba_legacy pull request #1200
Opened 2023-09-11 11:18 UTC by alvaro-ricotta

Simple hard fix for Avalanche icons on Earn page. 

![image](https://github.com/bobanetwork/boba/assets/81116391/98ce86ad-531e-44a1-aaa4-72f5453ba105)

2023-09-11 11:19 UTC, alvaro-ricotta commented
@sk-enya not sure what is EVO token, but we need to add this token into our tokenlist.

2023-09-12 17:22 UTC, InoMurko commented on packages/boba/gateway/src/util/coinImage.ts
> +  // hard fox for avax
🦊

2023-09-13 14:32 UTC, sk-enya commented
> @sk-enya not sure what is EVO token, but we need to add this token into our tokenlist.

for your reference @alvaro-ricotta 
https://support.avax.network/en/articles/6349868-what-does-the-e-suffix-in-the-token-name-mean-on-the-avalanche-bridge

2023-09-13 14:38 UTC, sk-enya requested changes
It looks confusing to user as you can the two different tokens with same icons.. 
as `.e` has some context and meaning to it like `it's bridge token on avax from ethereum` so better we should image icons like below.
![images](https://github.com/bobanetwork/boba/assets/86316370/e38ba895-2d06-4141-8e71-d81c746a7e81)

[refere link for more details](https://support.avax.network/en/articles/6349868-what-does-the-e-suffix-in-the-token-name-mean-on-the-avalanche-bridge)

let's get some help from @yhong1073 to get the icons prepared.



here is the list of icons which I found @yhong1073 can you please help to prepare icon design so we will make update it on gateway?

1. USDT.e
2. USDC.e
3. BUSD.e
4. DAI.e

2023-09-13 17:13 UTC, yhong1073 commented
[avax icons.zip](https://github.com/bobanetwork/boba/files/12600206/avax.icons.zip)

Here are the icons.

2023-09-13 17:22 UTC, alvaro-ricotta commented
Hey @sk-enya sounds good in that case, we can remove this PR and just update the tokenlist github, also @yhong1073 we need a icon for EVO token, not sure what token it´s , @InoMurko have some idea which token we´re talking about EVO?

2023-09-13 17:54 UTC, yhong1073 commented
![evo](https://github.com/bobanetwork/boba/assets/123016470/a5288d48-ef81-4f23-aaca-28381e50f052)
Here is the image for EVO. The image quality is bad because there were only low quality images for this logo.

2023-09-14 06:54 UTC, sk-enya commented
@alvaro-ricotta , I guess you are good to close this and update the token list repo itself

2023-09-14 11:30 UTC, alvaro-ricotta commented
@yhong1073 tokenlist only allow svg files, can you send a new version only with svgs? once i get it i´ll update our tokenlist repository

2023-09-14 16:05 UTC, yhong1073 commented
[svg icons.zip](https://github.com/bobanetwork/boba/files/12611047/svg.icons.zip)
Here are the svg versions of the icons.

2023-09-15 00:53 UTC, alvaro-ricotta commented
@sk-enya https://github.com/bobanetwork/token-list/pull/12 pr has been created, once we merge it we can close this pr.

2023-09-15 13:48 UTC, sk-enya commented
@alvaro-ricotta  https://github.com/bobanetwork/token-list/pull/12 has been merged!!

2023-09-15 13:49 UTC, alvaro-ricotta commented
This pr has been closed and remplaced by this branch https://github.com/bobanetwork/token-list/tree/feat/BobaLogov2

2023-09-15 13:49 UTC, closed without merging