Feat/reinitialized network switcher
bobanetwork/boba_legacy pull request #1206
Opened 2023-09-13 14:15 UTC by alvaro-ricotta

This commit includes an updated related to : 

The direct network switch from MetaMask has been enabled, the logic has been modified to automatically update balances in MM after changing the address, the logic has been modified to force a restart of the connection once the network is changed

[https://github.com/orgs/bobanetwork/projects/10/views/1?pane=issue&itemId=37030457](url)
[https://github.com/orgs/bobanetwork/projects/10/views/1?pane=issue&itemId=37848069](url)
[https://github.com/orgs/bobanetwork/projects/10/views/1?pane=issue&itemId=37848327](url)

2023-09-15 13:56 UTC, sk-enya requested changes
Please remove console which has been used for debugging purpose.

2023-09-15 13:56 UTC, sk-enya commented on packages/boba/gateway/src/containers/modals/dao/old/NewProposalModalOldDao.js
>          <Box sx={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
As you are working on this component. can you please get rid of importing `Box` from material ui and make use of `styled component` with typescript.

2023-09-15 13:56 UTC, sk-enya commented on packages/boba/gateway/src/hooks/useGasWatcher.ts
> +        console.log('im ethereum')
remove console please if it's not required

2023-09-15 13:56 UTC, sk-enya commented on packages/boba/gateway/src/hooks/useSwitchChain.ts
> +    console.log('switching change')
one more console please remove

2023-09-15 13:56 UTC, sk-enya commented on packages/boba/gateway/src/hooks/useWalletConnect.ts
> +        console.log('wrong network account', networkService.account)
please get rid of console here too.

2023-09-18 13:29 UTC, alvaro-ricotta commented on packages/boba/gateway/src/hooks/useWalletConnect.ts
> +        console.log('wrong network account', networkService.account)
Console log has been removed.

2023-09-18 13:29 UTC, alvaro-ricotta commented on packages/boba/gateway/src/hooks/useSwitchChain.ts
> +    console.log('switching change')
Console log has been removed.

2023-09-18 13:29 UTC, alvaro-ricotta commented on packages/boba/gateway/src/hooks/useGasWatcher.ts
> +        console.log('im ethereum')
Console log has been removed.

2023-09-18 16:17 UTC, sk-enya approved these changes
Change looks good, 

Please remove the consoles before merging to develop!

2023-09-20 11:13 UTC, sk-enya commented on packages/boba/gateway/src/services/networkService.js
> +    console.log(this.account)
please remove!

2023-09-20 11:50 UTC, merged

2023-09-27 06:07 UTC, sk-enya commented on packages/boba/gateway/src/hooks/useWalletConnect.ts
> -        dispatch(openModal('wrongNetworkModal'))
@alvaro-ricotta why did we remove here, I didn't capture this earlier but it's the issue here.