Feature : Sentry Integration + Text about the boba discounted fee.
bobanetwork/boba_legacy pull request #203
Opened 2022-06-20 17:37 UTC by sk-enya

- Sentry integration on gateway along with error handling in createActions.
- Avoid sending the sentry events on local server.
- Removed warnings!
- Added text besides the fee switch section to show using boba is discounted.

2022-06-22 08:13 UTC, InoMurko approved these changes
@Boyuan-Chen @souradeep-das @trangtran-enya wdyt?

2022-06-22 08:32 UTC, souradeep-das commented on packages/boba/gateway/src/actions/createAction.js
> +        Sentry.captureMessage(errorMessage.error.message);
does this capture all non-approved tx errors? do we want to capture these?

2022-06-23 06:07 UTC, sk-enya commented on packages/boba/gateway/src/actions/createAction.js
> +        Sentry.captureMessage(errorMessage.error.message);
Currently sentry is setup to collect all the errors and crash, I would like to know if we have exclude some errors from capturing.

@souradeep-das can you please help me with same.

2022-06-23 06:54 UTC, souradeep-das commented on packages/boba/gateway/src/actions/createAction.js
> +        Sentry.captureMessage(errorMessage.error.message);
I was wondering if capturing erc20 permit errors will be useful for us... but on second thoughts I think capturing everything would be better 👍 , we could always filter

2022-06-23 06:55 UTC, souradeep-das approved these changes

2022-06-24 01:00 UTC, Boyuan-Chen approved these changes
LGTM

2022-06-24 06:08 UTC, InoMurko commented
@sk-enya to make @java-spaces job easier-let's keep the PR description in form of: 
Why? (What was the issue)
How? (How was it resolved)

Tnx!

2022-06-24 06:08 UTC, InoMurko requested changes

2022-06-24 06:08 UTC, InoMurko commented on packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js
> +  // if (!accountEnabled) {
@sk-enya pls delete commented out code!

2022-06-24 06:28 UTC, InoMurko commented
Please also reference the ticket your PR is closing: https://github.com/bobanetwork/boba/issues/200

And close it after it's done! Tnx!

2022-06-24 08:31 UTC, sk-enya commented on packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js
> +  // if (!accountEnabled) {
Sure

2022-06-24 10:38 UTC, InoMurko approved these changes
please merge after cleanup and pr description!

2022-06-24 16:15 UTC, sk-enya commented on packages/boba/gateway/src/actions/createAction.js
> +        Sentry.captureMessage(errorMessage.error.message);
Okay then no changes required we are capturing everything as of now.

2022-06-24 21:07 UTC, merged