Wsdt/turing twitter
bobanetwork/boba_legacy pull request #238
Opened 2022-07-08 08:04 UTC by wsdt

## Overview

TwitterPay and AuthFaucet finalized (merge from TwitterPay branch). 

## Changes

- TwitterPay example
- Minor AuthFaucet changes

## Testing

Unit + integration tests (for smart contracts and python backend).

2022-07-08 12:15 UTC, InoMurko commented
has a few conflicts

2022-07-08 12:15 UTC, InoMurko commented
but looks good

2022-07-08 13:59 UTC, souradeep-das reviewed
looks good to me!
looks like some gateway and ops_boba changes needed to be made on the main files? If these changes are only associated with examples, do you think theres a way to consolidate example changes together separately?

2022-07-08 13:59 UTC, souradeep-das commented on ops_boba/api/metatransaction-api/serverless-mainnet.yml
> +  boba_getTestnetETH:
do we need this on mainnet?

2022-07-08 13:59 UTC, souradeep-das commented on packages/boba/register/addresses/addressesMainnet_0x8376ac6C3f73a25Dd994E0b0669ca7ee0C02F089.json
> +  "TwitterPay": ""
since we moved this to examples/, should we remove this?

2022-07-08 13:59 UTC, souradeep-das commented on packages/boba/register/addresses/addressesRinkeby_0x93A96D6A5beb1F661cf052722A1424CDDA3e9418.json
> +  "TwitterPay": "0xCE4FB6F28f261Eed9295C89B631eeDEE3FdC5B79"
since we moved this to examples/, should we remove this?

2022-07-10 15:21 UTC, wsdt commented
@InoMurko @souradeep-das merge conflicts resolved. TwitterPay is now removed from GateWay as it should be. 
Great catch thx!

2022-07-11 05:41 UTC, souradeep-das approved these changes
great!

2022-07-11 12:45 UTC, InoMurko requested changes

2022-07-11 12:45 UTC, InoMurko commented on packages/boba/gateway/src/util/common.js
> +export const asciiToHex = (str) => {
I think this isn't used!

2022-07-11 12:48 UTC, InoMurko commented on boba_examples/turing-twitter-pay/README.md
> +
ohhh, but what is this that is different?
what do you think about a sequence diagram?

We could turn this in a medium post as well? could you bring it up in #mkt with @java-spaces ?

2022-07-14 14:16 UTC, InoMurko approved these changes

2022-07-14 14:16 UTC, InoMurko commented on boba_examples/turing-twitter-pay/README.md
> +![TwitterPay](https://user-images.githubusercontent.com/28724551/178273125-8c4a634a-40ae-48ff-98ef-3fe4e55ff26d.png)
this is actually amazing. Could you engage Gian to perhaps prepare content (with other Hybrid Compute examples) on a medium page? Cc @java-spaces

2022-07-22 09:13 UTC, wsdt commented on boba_examples/turing-twitter-pay/README.md
> +![TwitterPay](https://user-images.githubusercontent.com/28724551/178273125-8c4a634a-40ae-48ff-98ef-3fe4e55ff26d.png)
sure! Will reach out to him, sorry didn't see your comment!

2022-07-22 10:10 UTC, merged