Add billing contract
bobanetwork/boba_legacy pull request #25
Opened 2022-03-19 18:12 UTC by trangtran-enya

2022-03-23 17:02 UTC, Boyuan-Chen requested changes

2022-03-23 17:02 UTC, Boyuan-Chen commented on packages/boba/contracts/package.json
> +    "lint": "yarn lint:fix && yarn lint:check",
We might not want to automatically fix the lint.

2022-03-23 17:08 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/L2BillingContract.sol
> +    }
How can we withdraw funds from this contract?

2022-03-23 17:08 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/L2BillingContract.sol
> +pragma solidity >0.7.5;
Can we use >0.8.9 to keep consistent with other contracts?

2022-03-23 17:08 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/L2BillingContract.sol
> +
Can we only keep one blank line between each function?

2022-04-01 06:25 UTC, souradeep-das commented on packages/boba/contracts/contracts/L2BillingContract.sol
> +        feeTokenAddress = _feeTokenAddress;
can we have checks input validation checks here, mainly the _feeTokenAddress != address(0), since initializer depends on it
(and if it makes sense for _l2FeeWallet and _exitFee as well)

2022-04-01 06:25 UTC, souradeep-das commented on packages/boba/contracts/contracts/L2BillingContract.sol
> +    modifier onlyInitiator() {
can we rename to onlyInitialized() and onlyNotInitialized() for consistency?

2022-04-01 06:25 UTC, souradeep-das commented on packages/boba/contracts/contracts/L2BillingContract.sol
> +        IERC20(feeTokenAddress).safeTransferFrom(_account, address(this), exitFee);
just a note:
since the exitFee is tweakable, we should be considerate on the approval step(not having infinite approval to the contract)

and also since, this can be called by anyone - only approve the max amount to be charged each time, if multiple approval is not desirable maybe we can make the call owner authenticated

2022-04-04 12:49 UTC, souradeep-das approved these changes

2022-04-06 01:31 UTC, CAPtheorem approved these changes

2022-04-06 01:31 UTC, merged