Update faq.md
bobanetwork/boba_legacy pull request #301
Opened 2022-08-16 14:22 UTC by java-spaces

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

I've added the completed Dev FAQ and added it here as per what Ino and I discussed.

## Changes

- I've added the entire Dev FAQ to the bottom of the page, including images and links to the documentation wherever necessary so that developers can better understand how to make use of everything available to them in the Boba Network

2022-08-16 14:37 UTC, Boyuan-Chen requested changes

2022-08-16 14:37 UTC, Boyuan-Chen commented on faq.md
> +
This is the test code. We don't need to include this.

2022-08-16 14:37 UTC, Boyuan-Chen commented on faq.md
> +The full details of this process [can be found in the docs](https://docs.boba.network/for-developers/verify-smart-contracts)
This is out of date. We are not using blockscout. Users can use the bobascan to verify the contracts or use the `[hardhat-etherscan](https://hardhat.org/hardhat-runner/plugins/nomiclabs-hardhat-etherscan#hardhat-etherscan)` plug to verify contracts.

2022-08-16 15:47 UTC, java-spaces commented on faq.md
> +The full details of this process [can be found in the docs](https://docs.boba.network/for-developers/verify-smart-contracts)
Ah, right. I'll delete this for now until I can get some new screenshots and included it in a v2

2022-08-16 15:47 UTC, java-spaces commented on faq.md
> +
Thanks for catching that, deleted now.

2022-08-17 08:52 UTC, InoMurko approved these changes

2022-08-26 18:03 UTC, Boyuan-Chen approved these changes

2022-08-26 18:03 UTC, merged