Add monitor for LayerZeroBridge
bobanetwork/boba_legacy pull request #312
Opened 2022-08-24 14:04 UTC by trangtran-enya

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Change 1
- Change 2
- ...

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

2022-08-24 19:44 UTC, Boyuan-Chen requested changes

2022-08-24 19:44 UTC, Boyuan-Chen commented on ops_boba/monitor/exec/test-monitor.js
> +  // await layerZeroBridgeMonitor.initConnection()
Delete the code if it's no needed?

2022-08-24 19:44 UTC, Boyuan-Chen commented on ops_boba/monitor/services/utilities/optimismEnv.js
> +const LAYER_ZERO_URL = env.LAYER_ZERO_URL || ''
We actually don't need this. The monitor service will deploy on Mainnet L2 and other L2s separately. The Monitor service only focus on its own L1 chain. We need to add an env `ops_boba/monitor/exec/run-monitor.js` to determine which layer zero monitor service that we want to run.

2022-09-02 12:27 UTC, souradeep-das approved these changes
lgtm!

2022-09-02 12:27 UTC, souradeep-das commented on ops_boba/monitor/package.json
> +    "trye": "node ./exec/try-monitor.js"
is this a typo?

2022-09-02 12:39 UTC, sk-enya commented on ops_boba/monitor/services/database.service.js
> +        : null
It should check for `receiptData.crossDomainMessageEstimateFinalizedTime` instead of `crossDomainMessage` right?

2022-09-02 12:39 UTC, sk-enya commented on ops_boba/monitor/services/database.service.js
> +      crossDomainMessageEstimateFinalizedTime=${bridgeData.crossDomainMessage
like above!

2022-09-02 12:39 UTC, sk-enya commented on ops_boba/monitor/services/utilities/optimismEnv.js
> +const { isJSDocThisTag } = require('typescript')
remove this unused import.

2022-09-02 12:43 UTC, Boyuan-Chen approved these changes

2022-09-02 13:50 UTC, boyuan-chen commented on ops_boba/monitor/exec/run-monitor.js
> +  ; (async () => {
Can we fix this lint?

2022-09-02 14:04 UTC, Boyuan-Chen commented on ops_boba/monitor/services/layerZeroBridge.js
> +const bridges = {
Please load contract addresses from 
```
const layerZeroMainnetAddresses = require('@boba/register/addresses/layerZeroMainnet.json')
 const layerZeroTestnetAddresses = require('@boba/register/addresses/layerZeroTestnet.json')
```

2022-09-02 20:32 UTC, sk-enya approved these changes
Looks Nice!

2022-09-05 16:52 UTC, trangtran-enya commented
Close to rebase to develop 
new PR https://github.com/bobanetwork/boba/pull/337

2022-09-05 16:52 UTC, closed without merging