[Gateway] : URL subpages on
bobanetwork/boba_legacy pull request #322
Opened 2022-08-26 09:37 UTC by sk-enya

closes https://github.com/bobanetwork/boba/issues/210

## Overview
Currently, we can not bookmark the gateway page as URLs don't show subpages.

## Changes

- Create the URL base page switching
- Refactor the footer link to use the router link
- Ecosystem category should load based on URL
- Create hooks for google analytics and send pageview to ga.
- Styling and Cleanup.

## Testing
All the navigation should work by changing the routes in URL.

2022-08-26 09:51 UTC, InoMurko approved these changes
🥇

2022-08-26 14:33 UTC, Boyuan-Chen requested changes
The `[MonsterVerse](http://localhost:3000/)` page is broken

2022-08-27 03:26 UTC, sk-enya commented
@Boyuan-Chen changes done and push can you please review.

2022-08-29 14:58 UTC, Boyuan-Chen approved these changes

2022-08-29 15:13 UTC, souradeep-das approved these changes

2022-08-29 17:04 UTC, merged