Add Boba Avalanche docs
bobanetwork/boba_legacy pull request #331
Opened 2022-09-02 13:42 UTC by Boyuan-Chen

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

Add Boba Avalanche docs

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Add docs

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

2022-09-20 08:16 UTC, InoMurko approved these changes

2022-09-21 06:33 UTC, InoMurko requested changes

2022-09-21 06:33 UTC, InoMurko commented on boba_documentation/developer/network-avalanche.md
> +| ChainID       | 43288                                                        |
43114

2022-09-21 07:33 UTC, InoMurko commented on boba_documentation/developer/network-avalanche.md
>  ## Boba Avalanche Links and Endpoints (tbd)
```suggestion
## Boba Avalanche Links and Endpoints 
```

2022-09-21 07:33 UTC, InoMurko commented on boba_documentation/developer/network-avalanche.md
>  ## Boba Avalanche Addresses (tbd)
```suggestion
## Boba Avalanche Addresses 
```

2022-09-21 07:39 UTC, InoMurko commented on boba_documentation/developer/network-avalanche.md
>  | ChainID       | 43288                                                        |
this is wrong:
```
curl https://testnet.avax.boba.network   -X POST   -H "Content-Type: application/json"   --data '{"method":"eth_chainId","params":[],"id":1,"jsonrpc":"2.0"}'
{"jsonrpc":"2.0","result":"0x10e8","id":1}
```

2022-09-21 15:51 UTC, Boyuan-Chen commented on boba_documentation/developer/network-avalanche.md
> +| ChainID       | 43288                                                        |
The chain Id for Bobaavax testnet is 4328.

2022-09-21 20:02 UTC, merged