Add Teleportation contract
bobanetwork/boba_legacy pull request #407
Opened 2022-10-10 21:16 UTC by Boyuan-Chen

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Change 1
- Change 2
- ...

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

2022-10-11 16:52 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +        onlyNotInitialized()
we could remove that here since `initializer()` already checks for initialization. 
https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/proxy/utils/Initializable.sol

2022-10-19 22:45 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        onlyNotInitialized()
Removed!

2022-10-19 23:49 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        onlyNotInitialized()
We must add it. Otherwise, it's reverted. 

Reason:

```
    bool public _initialized;

    /**
     * @dev Indicates that the contract is in the process of being initialized.
     */
    bool public _initializing;

    /**
     * @dev Modifier to protect an initializer function from being invoked twice.
     */
    modifier initializer() {
        require(_initializing || !_initialized, "Initializable: contract is already initialized");
   }

The `initializer()` reverted when `_initializing` and `_initialized` are `false`.
```

2022-10-20 12:25 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +// SPDX-License-Identifier: MIT
what is the status of this contract in terms of audits?

2022-10-20 15:50 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +// SPDX-License-Identifier: MIT
We can review it internally first. It takes serval days to add unit tests and integration tests, so it's better to send it for the audit before finishing everything.

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(msg.sender == disburser || disburser == address(0), 'Caller is not the disburser');
should we move away from "disburser == address(0)" pattern?
(like the newer contracts)

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(msg.sender == owner || owner == address(0), 'Caller is not the owner');
should we move away from "owner == address(0)" pattern?

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(BobaTokenAddress) != 0x4200000000000000000000000000000000000006, "Only not alt L2s can call this function");
how about "only non alt L2s"?

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(_amount >= minDepositAmount, "Deposit amount is too small");
should we just set '_amount = msg.value' instead of asking it as a param? to reduce cost?

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +                totalDisbursements[_sourceChainId] += 1;
do we want to make this unchecked though? since we use it above and its not limited

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            // Deliver the dispursement amount to the receiver. If the
```suggestion
            // Deliver the disbursement amount to the receiver. If the
```

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount, gas: 1000000 }("");
too much gas for native token transfer?

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +                totalDisbursements[_sourceChainId] += 1;
same as above

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            try IERC20(BobaTokenAddress).transfer(_addr, _amount) {
this should never fail? should we allow this to revert instead, if this ever does?

also should we use 'safeTransfer' for consistency

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        onlyDisburser()
minor: not sure how we want to do this- 
onlyOwner() or onlyDisburser() ?

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit MinDepositAmountSet(minDepositAmount, _minDepositAmount);
lets store the old value in a new var, and emit the event at the end?

applies for `setMaxAmount()` and `setMaxTransferAmountPerDay()` too

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/test/endToEndTests/teleportation.spec.ts
> +    it('should not disburse BOBA tokens if the depositId is worng', async () => {
minor
```suggestion
    it('should not disburse BOBA tokens if the depositId is wrong', async () => {
```

2022-10-21 19:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        __ReentrancyGuard_init_unchained();
reentrancy guard is unused as of now, any plans to use it?

2022-10-21 22:36 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            try IERC20(BobaTokenAddress).transfer(_addr, _amount) {
Ideally, it will never fail. `safeTransfer` is the internal function, so we can't wrap it into try{}catch{}.

Anyway, I will remove try{}catch{}.

2022-10-21 22:53 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit MinDepositAmountSet(minDepositAmount, _minDepositAmount);
I don't think we have to do that, since we don't fire txs based on the events.

2022-10-21 22:53 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        __ReentrancyGuard_init_unchained();
Remove!

2022-10-22 11:35 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit MinDepositAmountSet(minDepositAmount, _minDepositAmount);
true, but for convention and consistency, or maybe if someone else listens to the events?

2022-11-02 22:21 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit MinDepositAmountSet(minDepositAmount, _minDepositAmount);
Fixed!

2022-11-03 15:06 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> + */
if this contract is a mesh of Optimisms contracts, which I presume were audited, the better way of adding this contract is to:
1. add them unchanged
2. apply changes

this way we'd know from git what the diff is

2022-11-10 20:10 UTC, wsdt approved these changes
Looks good to me 🤔

2022-11-11 15:45 UTC, InoMurko commented on packages/boba/teleportation/README.md
> +| EVENT_PER_POLLING_INTERVAL  | The polling range of events             | 1000    |
what does this mean? number of blocks you're looking at for events?

yeah - this needs a better name. BLOCK_RANGE or similar

2022-11-11 15:46 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +  const TELEPORTATION_DISBURSER_KEY = config.str(
this is the private key that controls boba on source and destination chain, right?

2022-11-11 15:50 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _putDepositInfo(
whats the purpose of storing this on the filesystem?

2022-11-11 15:51 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
is this a filesystem database? why?

2022-11-11 15:52 UTC, InoMurko requested changes

2022-11-11 15:52 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _getEvents(
a number of functions don't have unit tests

2022-11-11 15:52 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/exec/run.ts
> +  const TELEPORTATION_DISBURSER_KEY = config.str(
It's the disburser key, not admin key.

2022-11-11 15:53 UTC, InoMurko commented
do we need finality protection debth (ie reorg)?

2022-11-11 15:53 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/service.ts
> +  async _putDepositInfo(
We store the last synced block, so it don't have to re-sync from the starting block, like the data transport layer.

2022-11-11 15:55 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/service.ts
> +  async _getEvents(
No, it's tested. `_getEvents` is nested in `_watchTeleportation`. The `_watchTeleportation` is tested.

2022-11-11 15:55 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
It's used for storing the last synced block.

2022-11-11 15:57 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _putDepositInfo(
DTL uses LevelDB, correct?

2022-11-11 15:57 UTC, Boyuan-Chen commented
> do we need finality protection debth (ie reorg)?

We don't have reorg on L2.

2022-11-11 15:57 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +  const TELEPORTATION_DISBURSER_KEY = config.str(
whats the difference?
in this scenario it's the private key that unlocks boba that's sent from A to B.

2022-11-11 15:58 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +  const TELEPORTATION_DISBURSER_KEY = config.str(
it's important that it hase enough liquidity

2022-11-11 15:58 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/service.ts
> +  async _putDepositInfo(
Yes, it's the same purpose.

2022-11-11 16:05 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/exec/run.ts
> +  const TELEPORTATION_DISBURSER_KEY = config.str(
The balance will be monitored in the monitor service. Disburser has some BOBA tokens and can disburse the BOBA token, but it doesn't control the contract (pause, unpause, parameters). 

The worst case of leaking the disburser key is that we lose all BOBA tokens in the disburser key, but BOBA tokens in the smart contract is safe. Only admin can withdraw BOBA token from the smart contract.

2022-11-11 16:21 UTC, souradeep-das approved these changes
new changes LGTM!

2022-11-11 18:38 UTC, Boyuan-Chen commented on packages/boba/teleportation/README.md
> +| EVENT_PER_POLLING_INTERVAL  | The polling range of events             | 1000    |
Updated the name to `BLOCK_RANGE_PER_POLLING`.

2022-11-14 15:27 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit BobaReceived(_toChainId, block.chainid, totalDeposits[_toChainId], msg.sender, _amount);
the naming of chainIds could be done better
what if we used `from` and `to`?
```
emit BobaReceived(_toChainId, block.chainid, totalDeposits[_toChainId], msg.sender, _amount);
```
teleport boba to `_toChainId ` from `block.chainid`, which increments nonce (index of totalDeposits, from the sender, for amount.

Is that right?

2022-11-14 15:55 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
you don't have to specify gas?

2022-11-14 15:56 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +            totalDisbursements[_sourceChainId] += 1;
unchecked?

2022-11-14 15:58 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +  const TELEPORTATION_DISBURSER_KEY = config.str(
does this private key always use BOBA to pay fees or will it need to hold ETH on boba eth?

2022-11-14 15:59 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
would using a managed postgres be better for performance and reliability?

2022-11-14 16:08 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _getEvents(
the idea behind a unit tests is to test the smallest, still testable unit - will it be a function or a method.
in _watchTeleportation, you're not testing only getEvents, but also 
```
try {
       lastBlock = await this._getDepositInfo(chainId)
     } catch (e) {
       this.logger.warn(`No deposit info found in chainId - ${chainId}`)
       lastBlock = depositTeleportation.height
       // store the new deposit info
       await this._putDepositInfo(chainId, lastBlock)
     }
```
So you're interested that `_getEvents` meets its design and behaves as intended.
- Does _getEvents really check all blocks that you've set from and to?
- Can you make sure that `_getEvents` stays within this.options.blockRangePerPolling?
- Can you make sure that `_getEvents` appends all events if endBlock needs chunking?
- Can you make sure that `_getEvents` includes all events from the contract queryFilter?

2022-11-14 16:08 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _getEvents(
same applies for `_putDepositInfo` that I think would benefit from more gradual testing

2022-11-14 16:35 UTC, boyuan-chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit BobaReceived(_toChainId, block.chainid, totalDeposits[_toChainId], msg.sender, _amount);
Yes

2022-11-14 16:35 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
Yup!

2022-11-14 16:37 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            totalDisbursements[_sourceChainId] += 1;
@souradeep-das 's comment for this `do we want to make this unchecked though? since we use it above and its not limited`, so I removed the unchecked. It costs a little more gas.

2022-11-14 16:42 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
I want to learn why! :-D

2022-11-14 16:53 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
I don't know exactly why, but I found this. https://github.com/ethereum/solidity/releases/tag/v0.6.4

2022-11-14 16:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
ahaa, nice catch! lets specify some gas here so the receiver does not get a lot of gas to play with

2022-11-14 17:00 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
Ok!

2022-11-14 17:02 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
I caught something 👌🏻🥇😂

2022-11-14 17:07 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
I don't think that's necessary. Even we lose the data, it only takes about 3 mins to sync up. We can also manually add it if we want to.

2022-11-14 17:08 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +        emit BobaReceived(_toChainId, block.chainid, totalDeposits[_toChainId], msg.sender, _amount);
Fixed

2022-11-14 17:08 UTC, boyuan-chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ value: _amount }("");
Added

2022-11-14 17:11 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
We can also increase the `eventPerPollingInterval` to speed up.

2022-11-14 17:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ gas: 21000, value: _amount }("");
great, does 21000 increase the gas ask by too much initially?
if it actually does, a normal transfer should use 2300, a little more than that should be good? (we can update though)

2022-11-14 17:43 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/Teleportation.sol
> +            (bool success, ) = _addr.call{ gas: 21000, value: _amount }("");
Updated to 3000.

2022-11-14 20:10 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
hmmm... if it takes 10 seconds to sync. why do it at all? wouldn't it be cleaner and simpler if you just dropped database and have a stateless service?

2022-11-14 20:11 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +          '0x4200000000000000000000000000000000000006'
should this be pulled out into a constant?

2022-11-14 20:12 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _disburseTx(
does this have a test?

2022-11-14 20:12 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
> +  async _disbureTeleportation(
```suggestion
  async _disburseTeleportation(
```
also, does this have a test?

2022-11-14 20:13 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/exec/run.ts
> +    dbPath: DATABASE_PATH,
Well currently it only takes about 2 or 3 seconds to sync. I mean it probably takes 1 minutes to sync in the future if we have 10M blocks. We can improve this in the future if we meet some problems.

2022-11-14 22:50 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/service.ts
> +          '0x4200000000000000000000000000000000000006'
Fixed

2022-11-14 22:50 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/service.ts
> +  async _disburseTx(
Added

2022-11-14 22:50 UTC, Boyuan-Chen commented on packages/boba/teleportation/src/service.ts
> +  async _disbureTeleportation(
Fixed

2022-11-15 17:42 UTC, InoMurko approved these changes
send it!

2022-11-22 10:20 UTC, merged