Expose Deposit to other account on bridge page.
bobanetwork/boba_legacy pull request #421
Opened 2022-10-20 22:52 UTC by sk-enya

:clipboard: Add associated issues, tickets, docs URL here.
closes: https://github.com/bobanetwork/boba/issues/393

## Overview

Enable deposit to other L2 account native bridging on gateway

## Changes

Enable deposit to other L2 account native bridging on gateway

## Testing

Connect to ethereum and you will have option to enable the deposit to L2 account on bridge screen.

2022-10-24 14:07 UTC, InoMurko requested changes

2022-10-24 14:07 UTC, InoMurko commented on packages/boba/gateway/src/util/masterConfig.js
> +        rpcUrl:  "https://rpc.ankr.com/eth_rinkeby",
can we pull this from env var please?

2022-10-24 14:08 UTC, InoMurko commented on packages/boba/gateway/src/util/masterConfig.js
> +        rpcUrl:  "https://rpc.ankr.com/eth_rinkeby",
also this:
```
name: "Rinkeby",
        chainId: 4,
        chainIdHex: '0x4',
```

2022-10-24 14:09 UTC, InoMurko commented on packages/boba/gateway/src/util/masterConfig.js
> +        rpcUrl:  "https://rpc.ankr.com/eth_rinkeby",
ah it seems this masterConfig.js is a pile of mess anyway hahaha

2022-10-24 14:09 UTC, InoMurko approved these changes

2022-10-24 14:20 UTC, souradeep-das approved these changes
LGTM 🚀

2022-10-24 19:12 UTC, sk-enya commented on packages/boba/gateway/src/util/masterConfig.js
> +        rpcUrl:  "https://rpc.ankr.com/eth_rinkeby",
Yeah sure will do that way...
it's good idea.

2022-10-24 19:30 UTC, sk-enya commented on packages/boba/gateway/src/util/masterConfig.js
> +        rpcUrl:  "https://rpc.ankr.com/eth_rinkeby",
@InoMurko I update this change can you please review once so I will be good to click on merge.

2022-10-25 11:02 UTC, InoMurko commented on packages/boba/gateway/.env.example
> +REACT_APP_RINKEBY_L2_RPC_URL=https://rinkeby.boba.network
this wasn't necessary as no other network is handled this way

2022-10-25 11:03 UTC, InoMurko commented on packages/boba/gateway/.env.example
> +REACT_APP_RINKEBY_L2_RPC_URL=https://rinkeby.boba.network
based on this https://github.com/bobanetwork/boba/pull/421#discussion_r1003362694

2022-10-25 19:08 UTC, sk-enya commented on packages/boba/gateway/.env.example
> +REACT_APP_RINKEBY_L2_RPC_URL=https://rinkeby.boba.network
okay got it reverting it back.

2022-10-26 11:45 UTC, Mrzeven commented
Would love to see direct Visa/mastercard deposits into boba

2022-11-03 15:05 UTC, InoMurko commented
can we merge this?

2022-11-09 12:43 UTC, merged