Inomurko/boba on goerli
bobanetwork/boba_legacy pull request #460
Opened 2022-11-17 10:53 UTC by InoMurko

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Change 1
- Change 2
- ...

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

2022-11-18 14:37 UTC, souradeep-das approved these changes

2022-11-18 23:22 UTC, Boyuan-Chen requested changes

2022-11-18 23:22 UTC, Boyuan-Chen commented on boba_documentation/developer/bridge-l1-and-l2/standard-bridge.md
> +| Goerli | [Goerli Boba Token List](https://github.com/bobanetwork/boba/blob/develop/packages/boba/register/addresses/addressesGoerli_0x93A96D6A5beb1F661cf052722A1424CDDA3e9418.json) |
The file name is wrong

2022-11-18 23:22 UTC, Boyuan-Chen commented on boba_documentation/developer/developer-start.md
> +The [Mainnet blockexplorer](https://blockexplorer.boba.network) and the [Goerli blockexplorer](https://blockexplorer.goerli.boba.network) are similar to Etherscan. The [Mainnet gateway](https://gatew
Maybe use `https://testnet.bobascan.com`?

2022-11-18 23:22 UTC, Boyuan-Chen commented on boba_documentation/developer/exchange-integration.md
> +| Goerli | [Goerli Boba Token List](https://github.com/bobanetwork/boba/blob/develop/packages/boba/register/addresses/addressesGoerli_0x93A96D6A5beb1F661cf052722A1424CDDA3e9418.json) |
The file name is wrong

2022-11-18 23:22 UTC, Boyuan-Chen commented on boba_documentation/developer/exchange-integration.md
> +| Goerli | [Goerli Boba Token List](https://github.com/bobanetwork/boba/blob/develop/packages/boba/register/addresses/addressesGoerli_0x93A96D6A5beb1F661cf052722A1424CDDA3e9418.json) |
The file name is wrong

2022-11-18 23:22 UTC, Boyuan-Chen commented on boba_documentation/developer/network-parameters.md
> +| Blockexplorer   | [https://blockexplorer.goerli.boba.network](https://blockexplorer.goerli.boba.network) |
Use `https://testnet.bobascan.com`?

2022-11-19 00:01 UTC, InoMurko commented on boba_documentation/developer/bridge-l1-and-l2/standard-bridge.md
> +| Goerli | [Goerli Boba Token List](https://github.com/bobanetwork/boba/blob/develop/packages/boba/register/addresses/addressesGoerli_0x93A96D6A5beb1F661cf052722A1424CDDA3e9418.json) |
Uhhhhi see it!

2022-11-19 20:04 UTC, merged