Add BobaLink service
bobanetwork/boba_legacy pull request #481
Opened 2022-11-29 02:25 UTC by Boyuan-Chen

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Change 1
- Change 2
- ...

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

2022-11-29 02:29 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public chainLinkLatestRoundId;
Record the chainLink's latestRoundId

2022-11-29 02:29 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public overrideStaringRoundId;
Record the starting round Id

2022-11-29 02:29 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    }
Add logic of overriding the `_startingRound` when the first oracle is added.

2022-12-01 08:47 UTC, wsdt commented on boba_documentation/developer/bobalink.md
> +The core idea of BobaLink is to use [Turing](./turing.md) in L2 smart contract to call outside API endpoint and write the price feed data to it. The API endpoint gets the price feed from the ChainLin
non-dev related, but did we actually check if it's "ok" to pull the data from their free L1 service into L2's? 
Not that there is some license attached to it that we are not aware of.

2022-12-01 08:51 UTC, wsdt approved these changes
looks fine to me - left a comment (not sure if you have an answer to that)

2022-12-01 20:54 UTC, InoMurko commented on boba_documentation/developer/bobalink.md
> +The core idea of BobaLink is to use [Turing](./turing.md) in L2 smart contract to call outside API endpoint and write the price feed data to it. The API endpoint gets the price feed from the ChainLin
No proprietary data pushed to an open decentralized network

2022-12-01 21:06 UTC, wsdt commented on boba_documentation/developer/bobalink.md
> +The core idea of BobaLink is to use [Turing](./turing.md) in L2 smart contract to call outside API endpoint and write the price feed data to it. The API endpoint gets the price feed from the ChainLin
that's true - but my concern was more about "how we use their service" - because there might be some kind of license attached. Feels a bit like using their service in a way that they didn't intended to, that's why I asked.

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    require(_CLLatestRoundId >= _roundId && _CLLatestRoundId >= chainLinkLatestRoundId, "ChainLink latestRoundId is invalid");
should we move this check upwards?

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    uint32 _maxSubmissions,
minSubmissionCount and maxSubmissionCount can be hardcoded
since we probably accept only one submission for each round in this case? should we do it?

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  function requestNewRound()
this is also probably not used? should we remove or stick with this for consistency?

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public restartDelay;
do we expect multiple oracles to submit alternatively, or should we permanently set restartDelay to zero

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    timeout = _timeout;
i think, we would not require timeout as well? rounds probably won’t be timed out since there is only one submission?

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +
minor: could we move non private methods upwards? (Or) remove the "//private" comment line L824? 😄

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    if (reportingRoundId == 0) {
why do we override reportingRoundId and latestRoundId for each addition of oracle? wondering, could we just note the startingId for oracle permissions?

2022-12-02 12:36 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   */
generally looks good that we are sticking to the same structure for FluxAggregator for consistency, but i think if we wanted, we could also simplify this to a barebone level to only serve the purpose, not sure which we should pick, opinions? 😄 
since we dont need multiple submitters, value aggregation etc on this contract things like - `roundDetails`, `updateRoundAnswer` and more could be minimized

2022-12-02 18:14 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    if (reportingRoundId == 0) {
I think it's better to keep the roundId consistent with ChainLink's contract, so developers can check that the same roundId should return the same price feed.

2022-12-02 18:17 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    if (reportingRoundId == 0) {
Also, we have this `chainLinkLatestRoundId` variable that allows the developers to know that if our contract is updated to the latest roundId.

2022-12-02 18:25 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +
Fixed

2022-12-02 18:27 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   */
I think we can simplify it and put it behind the proxy contract in case we need some updates in the future.

2022-12-03 10:00 UTC, InoMurko commented on integration-tests/test/bobalink.spec.ts
> +    const server = module.exports = http.createServer(async function (req, res) {
I love this

2022-12-03 10:02 UTC, InoMurko commented on packages/boba/bobalink/.env.example
> +SET_GAS_PRICE_TO_ZERO=
what are the defaults? could leave them here for clarity

2022-12-03 10:03 UTC, InoMurko commented on packages/boba/bobalink/README.md
> +| POLLING_INTERVAL      | The polling interval of fetching data   | 15000   |
you could set it to what the L1 block timming is. 12seconds!

2022-12-03 10:06 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public restartDelay;
what is restartDelay?

2022-12-03 10:07 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public restartDelay;
it seems like - just as you said, we basically would need just the barebone here. the interface without the chainlink logic

2022-12-03 10:08 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   */
yeah, that makes sense. should you make an issue so that we keep an eye on this - we could simplify it by alot and save gass

2022-12-05 05:29 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public restartDelay;
restartDelay is the number of rounds a `submitter` has to wait before they can initiate a subsequent round after initiating one 😄

2022-12-05 05:31 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  uint32 public restartDelay;
yeah a barebone logic could be easier i guess!

2022-12-05 05:38 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   */
yeah we can track this as an issue, although i'm scared we won't be able to minimize much even if we put it under a proxy (for the storage slots)

2022-12-05 05:41 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    if (reportingRoundId == 0) {
got it, yeah makes sense, so technically we just add one Oracle so the global value overrides are fine

2022-12-05 05:42 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   */
The core function that we will use is `submit()`. In that function, it verifies the price feed and roundId, etc. We can't simplify those checks. Other functions we probably won't use them, so we can simplify or remove them and put the contract under a proxy just in case.

2022-12-05 05:50 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   */
yeah, so we could remove the methods, but would have to stick to some of the elaborate storage structures

2022-12-06 17:50 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  address public turingChainLinkPriceFeedAddr;
I know you had good intentions. But these comments are pointless.
They either provide valuable insight, or they should be deleted.

2022-12-06 17:51 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    // hardcode
It would actually make more sense to explain what it means to have these two values set to 1. What is the consequence?

2022-12-06 18:00 UTC, boyuan-chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  address public turingChainLinkPriceFeedAddr;
Removed

2022-12-06 18:00 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    // hardcode
Removed

2022-12-06 18:01 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    require(_roundId == latestRoundId.add(1), "invalid roundId to initialize");
why was this additional check added here?

2022-12-06 18:03 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    require(_roundId == latestRoundId.add(1), "invalid roundId to initialize");
ah, moved up from `validateOracleRound`!

2022-12-06 18:03 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    require(_roundId == latestRoundId.add(1), "invalid roundId to initialize");
The original check is 
```
  function validateOracleRound(address _oracle, uint32 _roundId)
    private
    view
    returns (bytes memory)
  {
    // cache storage reads
    uint32 startingRound = oracles[_oracle].startingRound;
    uint32 rrId = reportingRoundId;

    if (startingRound == 0) return "not enabled oracle";
    if (startingRound > _roundId) return "not yet enabled oracle";
    if (oracles[_oracle].endingRound < _roundId) return "no longer allowed oracle";
    if (oracles[_oracle].lastReportedRound >= _roundId) return "cannot report on previous rounds";
    if (_roundId != rrId && _roundId != rrId.add(1) && !previousAndCurrentUnanswered(_roundId, rrId)) return "invalid round to report";
    if (_roundId != 1 && !supersedable(_roundId.sub(1))) return "previous round not supersedable";
  }
```
Since we want to simplify the contract as much as possible, the `startingRound` and `reportingRoundId` are not necessary needed. What the above check does is to make sure that the new round id is equal to the last round Id + 1.

2022-12-06 18:05 UTC, InoMurko requested changes

2022-12-06 18:05 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  function getOracle() external view returns (address) {
ehmmm, should we change the interface? I think we shouldn'!

2022-12-06 18:05 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  function getAdmin()
interface change!

2022-12-06 18:05 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  function transferOracleAdmin(address _oracleAdmin)
interface updated

2022-12-06 18:08 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    require(_roundId == latestRoundId.add(1), "invalid roundId to initialize");
yep, I figured, thanks!

2022-12-07 06:57 UTC, souradeep-das reviewed
looks great!

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +import "@chainlink/contracts/src/v0.6/Median.sol";
can we remove the unused libraries? 😄

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  event UpdateTuringUrl(
minor: for consistency, should we rename this and the following events to format- TuringUrlUpdated

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    oracleAddress = _added;
lets add a `_added != address(0)` check too? since we expect this to be called once and latestRoundId to be set once

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   * update the round related parameters that pertain to total oracle count
minor: some of these docu needs to be updated

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +   * @param _added is the list of addresses for the new Oracles being added
```suggestion
   * @param _added is the address of the new Oracle being added
```

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    address prevOracleAdmin = oracleAdmin;
lets add a _oracleAdmin zero addr check

2022-12-07 06:57 UTC, souradeep-das commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    onlyOracleAdmin
the chainlink contracts have the `oracle` address to submit instead, and the admin for withdrawing funds, whereas in ours oracleAdmins role is quite nonexistent.
How do we communicate this? Either way we do, one address will be unused, do we want to set both the addresses to be the same?

2022-12-07 23:17 UTC, Boyuan-Chen commented on packages/boba/bobalink/.env.example
> +SET_GAS_PRICE_TO_ZERO=
Fixed

2022-12-07 23:17 UTC, Boyuan-Chen commented on packages/boba/bobalink/README.md
> +| POLLING_INTERVAL      | The polling interval of fetching data   | 15000   |
Fixed

2022-12-07 23:17 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +  event UpdateTuringUrl(
Fixed

2022-12-07 23:18 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    oracleAddress = _added;
Added

2022-12-07 23:18 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    address prevOracleAdmin = oracleAdmin;
Added

2022-12-07 23:20 UTC, boyuan-chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    onlyOracleAdmin
We can mention that `This contract is simplified a lot to only serve the purpose of using HC to submit L1 data, so we only keep the admin for submitting data and remove the admin role for withdrawing funds.`.

2022-12-08 04:47 UTC, InoMurko requested changes

2022-12-08 04:47 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +import "./interfaces/IHybirdComputeHelper.sol";
`import "./interfaces/IHybridComputeHelper.sol";`

2022-12-08 04:47 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    bytes memory encResponse = HCHelper.TuringTx(HCUrl, encRequest);
should you use TuringTxv2?

2022-12-08 04:47 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/interfaces/IHybirdComputeHelper.sol
> +interface IHybirdComputeHelper {
`IHybridComputeHelper`

2022-12-08 04:53 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    bytes memory encResponse = HCHelper.TuringTx(HCUrl, encRequest);
V2 is designed for the long response. Do we want to use that?

2022-12-08 04:55 UTC, InoMurko commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    bytes memory encResponse = HCHelper.TuringTx(HCUrl, encRequest);
as far as I'm concerned - V1 is broken, V2 is fixed 🍡 🍡 🍡 
idk, what do you think?

2022-12-08 04:57 UTC, Boyuan-Chen commented on packages/boba/contracts/contracts/oracle/FluxAggregatorHC.sol
> +    bytes memory encResponse = HCHelper.TuringTx(HCUrl, encRequest);
I am ok with V0. BTW, we don't have any docs for V2.

2022-12-08 04:59 UTC, InoMurko approved these changes
good stuff ser

2022-12-08 05:51 UTC, souradeep-das approved these changes
to the moon 🚀

2022-12-08 11:36 UTC, merged