fix: add-babylons
bobanetwork/boba_legacy pull request #482
Opened 2022-11-29 07:05 UTC by yecandir

Add babylons to ecosystem

2022-12-06 06:34 UTC, sk-enya commented
@yecandir can you please resolve conflict.

2022-12-29 06:50 UTC, Boyuan-Chen commented
@yecandir Could you please fix the conflict?

2023-01-16 07:45 UTC, sk-enya requested changes

2023-01-16 07:45 UTC, sk-enya commented on packages/boba/gateway/src/containers/ecosystem/project.list.js
> +    "type": "NFT Marketplace and web3.0 Infrastructure Services",
@yecandir value of type should be between the list below 
``` 
const typeOrder = ['defi', 'gamefi', 'nft', 'bridge', 'wallet', 'tool', 'token']
```
So it will be visible on ecosystem page.

2023-01-16 07:57 UTC, sk-enya commented
Closing this as updated changes with PR https://github.com/bobanetwork/boba/pull/518

2023-01-16 07:57 UTC, closed without merging