[AA] tests: add integrations tests for AA bundler, wallets, paymaster
bobanetwork/boba_legacy pull request #562
Opened 2023-02-03 12:26 UTC by souradeep-das

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Describe what your Pull Request is about in a few sentences.

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Change 1
- Change 2
- ...

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.

2023-02-08 18:36 UTC, InoMurko commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +  it('{tag:other} should be able to send a userOperation to a wallet through the bundler', async () => {
tags can be dropped these days! fyi

2023-02-08 18:37 UTC, InoMurko commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +import chai from 'chai'
on the offchance that someone - a developer - looks at these integration tests - could you describe their intend a bit better? maybe from setup to what they actually plan to cover

2023-02-08 18:39 UTC, InoMurko commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +      )
my question is - is this the right separation between `setup` and `test`?
and this isn't

2023-02-08 18:40 UTC, InoMurko commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +        throw new Error('Submission to Bundler Failed')
maybe throw e too?

2023-02-08 18:40 UTC, InoMurko commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +      maxPriorityFeePerGas: '0x59682F00',
where do these constants come from?

2023-02-22 15:56 UTC, souradeep-das commented on integration-tests/test/boba_aa_sponsoring_fee.spec.ts
> +    it('should be able to add paymaster stake ', async () => {
is splitting this into multiple assertions any better? or should i keep it under one block like `boba_aa_fee_alt_token.spec.ts`

2023-02-22 15:58 UTC, souradeep-das commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +      maxPriorityFeePerGas: '0x59682F00',
changed to make the sdk fetch gasPrice and use those values

2023-02-22 15:59 UTC, souradeep-das commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +      )
thanks, tried to refactor it. Related to this, wdyt about https://github.com/bobanetwork/boba/pull/562#discussion_r1114550985?

2023-02-24 18:58 UTC, Boyuan-Chen commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +    try {
Do we want to skip the test if anything goes wrong?

2023-03-21 15:52 UTC, souradeep-das commented on integration-tests/test/boba_aa_fee_alt_token.spec.ts
> +    try {
the `sendUserOpToBundler()` operation seems to require a try catch, if it fails something is wrong - so lets make throw an error!

2023-03-21 15:56 UTC, InoMurko commented on integration-tests/hardhat.config.ts
> +        version: '0.8.12', // Required for WETH9
https://github.com/bobanetwork/boba/issues/668

2023-03-21 18:57 UTC, InoMurko commented on packages/boba/bundler_sdk/src/calcPreVerificationGas.ts
> +    p.signature = hexlify(Buffer.alloc(ov.sigSize, 1))
why is the dummy signature twice?
line 66 has dummy signature set - does that mean that the merge with userOp would overwrite it?

2023-03-21 18:58 UTC, InoMurko commented on packages/boba/bundler_sdk/src/calcPreVerificationGas.ts
> +    p.signature = hexlify(Buffer.alloc(ov.sigSize, 1))
it makes sense then to remove the line on 66

2023-03-21 19:01 UTC, InoMurko commented on packages/boba/bundler_sdk/src/Provider.ts
> +  originalSigner: Signer = originalProvider.getSigner(),
do you want to update the `param` docs above the function definition?

2023-03-21 19:01 UTC, InoMurko commented on packages/boba/bundler_sdk/src/Provider.ts
> +  originalSigner: Signer = originalProvider.getSigner(),
why does it make sense to defer ownership to a wallet?

2023-03-21 19:09 UTC, InoMurko commented on packages/boba/bundler/src/UserOpMethodHandler.ts
> +    // await this.simulateUserOp(userOp1, entryPointInput)
```suggestion
    //this is doing the geth debug_traceCall that the current ORU doesn't support
    // await this.simulateUserOp(userOp1, entryPointInput)
```

2023-03-21 19:20 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_sponsoring_fee.spec.ts
> +        const requestId = await bundlerProvider.sendUserOpToBundler(signedOp)
I don't like the (hidden) dependency between tests on `signedOp`!  it seems  the previous test should be a setup(before_all) and the expect statement in a separate test?

2023-03-21 19:21 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_sponsoring_fee.spec.ts
> +    })
why does this test belong in the group where the user doesn't have a fee token?

2023-03-21 19:26 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +  it('A user without ETH pays for a tx using $BOBA through a paymaster', async () => {
just to make things clear - ofc this does not mean it's using BOBA as the secondary fee token on the network

2023-03-21 19:27 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +  it('A user without ETH pays for a tx using $BOBA through a paymaster', async () => {
the paymaster could be accepting any token erc20 and pay for the userOp with it's own Eth as a wallet enabler

2023-03-21 19:28 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +        throw new Error('Submission to Bundler Failed: ' + e)
does this happen at all? in tests? would perhaps make more sense to just check on the txid with `expect` rather that a try catch imo

2023-03-21 19:31 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +    // TODO: check why paymasterAndData does not work when added to the walletAPI
you mentioned this is an optimisation, what does it give?

2023-03-21 19:32 UTC, InoMurko commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +      throw new Error('Submission to Bundler Failed: ' + e)
this is a huge try catch - I would rather see if we can avoid this

2023-03-21 19:35 UTC, InoMurko requested changes
I would just suggest polishing a few things - like the big try/catch statements that might catch things out of their scope and then we're good!

2023-03-22 01:15 UTC, Boyuan-Chen commented
Can we add tests to the alt-l2 test folder?

2023-03-22 10:37 UTC, InoMurko commented on integration-tests/test/boba_aa_sponsoring_fee.spec.ts
> +    it('should be able to add paymaster stake ', async () => {
imo tests shouldn't be coupled - there shouldn't be a dependency between them. what do you think?

2023-03-22 12:12 UTC, souradeep-das commented on packages/boba/bundler_sdk/src/Provider.ts
> +  originalSigner: Signer = originalProvider.getSigner(),
updated the param docs, thanks!

boba does not allow eth_sendTransaction from a remoteSigner, so we override using a wallet ([sdk issue-3](https://github.com/bobanetwork/boba/issues/576))

2023-03-22 12:14 UTC, souradeep-das commented on packages/boba/bundler/src/UserOpMethodHandler.ts
> +    // await this.simulateUserOp(userOp1, entryPointInput)
added

2023-03-22 12:15 UTC, souradeep-das commented on integration-tests/test/eth-l2/boba_aa_sponsoring_fee.spec.ts
> +    })
rephrased the it statement
This step is where the paymaster operator funds the paymaster

2023-03-22 12:15 UTC, souradeep-das commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +  it('A user without ETH pays for a tx using $BOBA through a paymaster', async () => {
rephrased and added a comment

2023-03-22 12:18 UTC, souradeep-das commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +    // TODO: check why paymasterAndData does not work when added to the walletAPI
it would allow to specify the paymasterAPI param in the walletAPI object from the sdk once and use it throughout. Right now we are self adding the 'paymaster' field to the constructed userOp, which can be prevented. makes it easier!

2023-03-22 12:24 UTC, souradeep-das commented on integration-tests/test/boba_aa_sponsoring_fee.spec.ts
> +    it('should be able to add paymaster stake ', async () => {
makes sense. 
The setup/it blocks looked huge and with a lot of steps, so tried to split them into multiple intermediary steps, but which would have these dependencies
Although i have put them under a separate new describe block, that contains all the dependent steps.

Do you think i should back to one it block? trading a bit of readability

2023-03-22 12:27 UTC, InoMurko commented on integration-tests/test/boba_aa_sponsoring_fee.spec.ts
> +    it('should be able to add paymaster stake ', async () => {
I don't see a problem with a huge setup - it is what it is. 
Perhaps it makes sense to split them into separate files (even if the setup repeats). 

As long as tests are not coupled.

2023-03-22 12:28 UTC, InoMurko commented
> Can we add tests to the alt-l2 test folder?

that makes sense yeah!

2023-03-22 12:28 UTC, InoMurko commented
> > Can we add tests to the alt-l2 test folder?
> 
> that makes sense yeah!

you could do it in a follow up PR too though.

2023-03-22 12:29 UTC, souradeep-das commented
> Can we add tests to the alt-l2 test folder?

oh yes, the GPOPaymaster is specifically for alt-l2, will add that + aa_wallet test

2023-03-22 12:33 UTC, souradeep-das commented on integration-tests/test/boba_aa_sponsoring_fee.spec.ts
> +    it('should be able to add paymaster stake ', async () => {
okayy

2023-03-22 14:01 UTC, souradeep-das commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +      throw new Error('Submission to Bundler Failed: ' + e)
dont know why i need this before for the sendUserOptoBundler operation, but it works without now - removed

2023-03-22 14:02 UTC, souradeep-das commented on integration-tests/test/eth-l2/boba_aa_fee_boba.spec.ts
> +        throw new Error('Submission to Bundler Failed: ' + e)
rmd

2023-03-22 14:03 UTC, souradeep-das commented on integration-tests/test/boba_aa_sponsoring_fee.spec.ts
> +    it('should be able to add paymaster stake ', async () => {
how about now ?

2023-03-22 14:07 UTC, souradeep-das commented on packages/boba/bundler_sdk/src/calcPreVerificationGas.ts
> +    p.signature = hexlify(Buffer.alloc(ov.sigSize, 1))
L66 is for when userOp.signature doesn't exist, and L71 for when its empty. 
I can combine them together, but is keeping this as an addition better for pulling changes in the future?

2023-03-22 14:16 UTC, souradeep-das commented
moving the alt-l1 tests to a new PR, because it involves tests for a new contract
tracked here: https://github.com/bobanetwork/boba/issues/670

2023-03-22 14:57 UTC, InoMurko approved these changes

2023-03-22 16:47 UTC, Boyuan-Chen approved these changes

2023-03-23 06:44 UTC, merged