Wavect/mockups: Design alignment
bobanetwork/boba_legacy pull request #595
Opened 2023-02-17 11:49 UTC by wavect-gmbh

## Overview

First adaptations to the Figma mockups, related to #335 (most work done on the Bridge page)

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- redesigned colors, margins, overall design on bobaBridge when connected
- fixed margins next to the IconSwitcher
- redesign bobaBridge 'when not connected'
- fixed all "Ethereum" spelling mistakes
- redesigned bobaBridge - changed some colors, variants, sizes
- align new design (1.02) to footer

## Testing

Describe how to test your new feature/bug fix and if possible, a step by step guide on how to demo this.
- Local tests
- P2P review with @wsdt

2023-02-17 12:23 UTC, wsdt approved these changes
Good work David (we tested it out locally P2P). 
Waiting for merge conflicts to be resolved.

2023-02-24 13:21 UTC, wsdt commented
@InoMurko @sk-enya please review & merge to keep PR's smaller.

2023-02-24 13:22 UTC, this-dave commented
Changes from todays weekly push:
- redesigned the LayerSwitcher
- redesigned Wallet page when connected including tab colors, connection-part, connect-button
- redesigned Ecosystem page (adjustments to some background colors and hover effect)
- redesigned History page according to current figma design (there was no figma design of "History", so I made changes on my own to fit the rest of the design)
- redesigned/reworked the Tooltip Component + adjusted the tooltip prop in the Button component according to the Tooltip component
- adjustments to the PageHeader
- some changes to the index.js  (Tooltip style overwrite)
- adjusted Social Media icon hover + fixed Discord Icon hover
- some overall small adjustments

2023-02-24 13:33 UTC, InoMurko commented
I trust your judgment!

2023-02-24 13:33 UTC, InoMurko approved these changes

2023-02-27 06:59 UTC, sk-enya commented
On the history page, some text seems to overlap please ref the screenshot below.
![Screenshot 2023-02-27 at 12 21 58 PM](https://user-images.githubusercontent.com/86316370/221494876-391572cb-aecf-4e8e-8bb6-5eeed1b7385a.png)

@InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.

Old :
![Screenshot 2023-02-27 at 12 27 10 PM](https://user-images.githubusercontent.com/86316370/221495154-0be66774-8c92-47c5-84cc-eff5a15efa22.png)

Redesigned one:
![Screenshot 2023-02-27 at 12 27 31 PM](https://user-images.githubusercontent.com/86316370/221495229-f0a70c4b-074b-475e-b0e7-3e445d75e921.png)

2023-02-27 06:59 UTC, sk-enya requested changes

2023-02-27 06:59 UTC, sk-enya commented on packages/boba/gateway/src/components/pageHeader/PageHeader.js
> +          <FeeSwitcher />
FeeSwitcher only needs to be enable for layer l2, can you please fix it.
`{layer === LAYER.L2 ? <FeeSwitcher /> : null}`

2023-02-27 06:59 UTC, sk-enya commented on packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js
> +        </Typography>
There should be HelpOutline Icon which shows tooltip on hover.
Seems like **fee** getting added multiple times.

![Screenshot 2023-02-27 at 11 54 38 AM](https://user-images.githubusercontent.com/86316370/221490448-fe414ed7-aa5a-4d04-9316-2599161e2c24.png)

2023-02-27 06:59 UTC, sk-enya commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
Can you please **userPrompt** back as its only rendering the connect button other page as the userPrompts added intentionally.

Earlier :
![Screenshot 2023-02-27 at 12 00 02 PM](https://user-images.githubusercontent.com/86316370/221491199-02dd19e6-421d-4791-ae6e-f53d61fa446a.png)

After your change:
![Screenshot 2023-02-27 at 11 59 53 AM](https://user-images.githubusercontent.com/86316370/221491223-e9d58a87-6c74-402b-8987-8c0db5bfa630.png)


Which is affecting on other pages well please take look

2023-02-27 06:59 UTC, sk-enya commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
Button design looks good!

2023-02-27 09:25 UTC, wsdt commented
> On the history page, some text seems to overlap please ref the screenshot below. ![Screenshot 2023-02-27 at 12 21 58 PM](https://user-images.githubusercontent.com/86316370/221494876-391572cb-aecf-4e8e-8bb6-5eeed1b7385a.png)
> 
> @InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.
> 
> Old : ![Screenshot 2023-02-27 at 12 27 10 PM](https://user-images.githubusercontent.com/86316370/221495154-0be66774-8c92-47c5-84cc-eff5a15efa22.png)
> 
> Redesigned one: ![Screenshot 2023-02-27 at 12 27 31 PM](https://user-images.githubusercontent.com/86316370/221495229-f0a70c4b-074b-475e-b0e7-3e445d75e921.png)

That was already the case before starting the work, created an issue for this: 
https://github.com/bobanetwork/boba/issues/603

@this-dave

2023-02-27 09:28 UTC, wsdt commented on packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js
> +        </Typography>
Good take on the double fee! 
But the HelpOutline icon is missing in the Figma design as well. But we can add it again.

2023-02-27 09:30 UTC, InoMurko commented
> > On the history page, some text seems to overlap please ref the screenshot below. ![Screenshot 2023-02-27 at 12 21 58 PM](https://user-images.githubusercontent.com/86316370/221494876-391572cb-aecf-4e8e-8bb6-5eeed1b7385a.png)
> > @InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.
> > Old : ![Screenshot 2023-02-27 at 12 27 10 PM](https://user-images.githubusercontent.com/86316370/221495154-0be66774-8c92-47c5-84cc-eff5a15efa22.png)
> > Redesigned one: ![Screenshot 2023-02-27 at 12 27 31 PM](https://user-images.githubusercontent.com/86316370/221495229-f0a70c4b-074b-475e-b0e7-3e445d75e921.png)
> 
> That was already the case before starting the work, created an issue for this: #603
> 
> @this-dave

We could trim the transaction hashes similar to how Safe is doing them:
<img width="483" alt="image" src="https://user-images.githubusercontent.com/2582555/221525990-10c1de8e-508f-4156-9fe3-6c3b8cfe85cb.png">


The redesigned one for socials and other links look much better, thanks

2023-02-27 09:30 UTC, wsdt commented
> @InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.

@sk-enya @InoMurko The new design is according to the mockups - shouldn't we settle for a design first before implementing it?

2023-02-27 09:31 UTC, wsdt commented
> 0x38e8...kjfk

@InoMurko exactly already on it

2023-02-27 09:32 UTC, InoMurko commented
> > @InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.
> 
> 
> 
> @sk-enya @InoMurko The new design is according to the mockups - shouldn't we settle for a design first before implementing it? Looking forward to your feedback


I agree. Let me know what you need from me.

2023-02-27 09:33 UTC, wsdt commented on packages/boba/gateway/src/components/pageHeader/PageHeader.js
> +          <FeeSwitcher />
Makes sense! Will be done

2023-02-27 09:36 UTC, wsdt commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
prefer a CTA message too, but doesn't look like we have a design for it. So, to clarify you want to just replace the new button with the previous highlighted section?

2023-02-27 10:08 UTC, sk-enya commented on packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js
> +        </Typography>
yeah, it was added later by dev itself.

2023-02-27 10:11 UTC, sk-enya commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
Would be great if you have a better suggestion on this, yeah this is not in the design but was added by Jan previously.

2023-02-27 10:13 UTC, sk-enya commented
> > @InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.
> 
> @sk-enya @InoMurko The new design is according to the mockups - shouldn't we settle for a design first before implementing it? Looking forward to your feedback

Yeah @wsdt, seems like most of the design changes have been already done and I was expecting @InoMurko views on the footer design which he has already shared so no changes are required!

2023-02-27 10:39 UTC, wsdt commented on packages/boba/gateway/src/components/mainMenu/feeSwitcher/FeeSwitcher.js
> +        </Typography>
noted, already added to our issue! @this-dave FYI

2023-02-27 10:40 UTC, wsdt commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
ok will leave this to @this-dave as he is more creative than me :-) thx! will create an issue

2023-02-27 10:42 UTC, wsdt commented
> > > @InoMurko would love to know your thoughts footer design and placement part, as I feel keeping social links for bobanetwork and the boba website link together.
> > 
> > 
> > @sk-enya @InoMurko The new design is according to the mockups - shouldn't we settle for a design first before implementing it? Looking forward to your feedback
> 
> Yeah @wsdt, seems like most of the design changes have been already done and I was expecting @InoMurko views on the footer design which he has already shared so no changes are required on the footer all good!

ok awesome, thanks @sk-enya !

2023-02-27 14:05 UTC, this-dave commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
@sk-enya So do you want that the old user prompt is displayed on all sites again and also move the connect button to the box (like on the wallet page) instead of the current (live) "no data" icon as it is in the design files? (Image 2)

Or do you want the whole old user prompt back and just implement an additional connect button in the box like on this picture (there would be two 'connect' buttons then):
![brave_ic9Kd2hLOz](https://user-images.githubusercontent.com/49922326/221581685-15ecdb06-8e05-46c8-b811-0b7f7ba90a54.png)

There are no big changes on the history page, but on the wallet page, for example, the "Connect" button has been moved to the field where the data is displayed.

So there are three possible solutions:
- 1) Bring back the older user prompt and just redesign it (connect button will stay in place)
- 2) Bring back the older user prompt (with a redesign) and move the button as in the Figma design approach (for example: into the box on the wallet page)
- 3) Bring back the old user prompt (with redesign) but add a connect button additional (like to the box on the wallet page)

How should I fix it? For me, I think 1) or 2) is the best because on 3) you have two connect buttons that are not needed

Visualized here:
![boba2702](https://user-images.githubusercontent.com/49922326/221581285-f14c483f-2c6f-49a0-9472-0ebfb10dc250.png)

2023-02-27 14:27 UTC, sk-enya commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
@this-dave on the wallet page it doesn't make sense to show the Token and NFT tab before connecting to Metamask.

I would suggest just keeping only the top box with the userPrompt and connect button like the history page.

![Screenshot 2023-02-27 at 7 55 21 PM](https://user-images.githubusercontent.com/86316370/221589795-4c4a778a-b0c2-4af5-af82-81a8761e8da9.png)

2023-02-28 09:44 UTC, wsdt commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
sure, the change will be incorporated! Thanks for the clarification. Could be beneficial if we have these kind of differences to the mockup somewhere documented, otherwise the mockups are implemented exactly as is and then have to be partially reversed in the PR. Any chance we could do this @sk-enya ?

2023-02-28 14:52 UTC, sk-enya commented on packages/boba/gateway/src/containers/connect/Connect.js
> +      </Button>
Yeah @wsdt Absolutely to save developer efforts this needs to be documented somewhere, prepared the issue for this as of now so we can come back to this later [#608](https://github.com/bobanetwork/boba/issues/608)

2023-03-01 15:46 UTC, wsdt commented
We just had a live review, looks good to me. Will review the code now.

2023-03-01 15:56 UTC, wsdt approved these changes
One thing @this-dave noted was that we may want to use the prettier-formatting config we have in the repo to keep changes low. Sahil had the same issue when he began working on the Gateway. 

This could help avoiding merge conflicts in future. But is out of scope here.

2023-03-01 15:59 UTC, this-dave commented
**Fixed all issues including:**
- brought back user prompt with new Figma design
- fee is now only shown when connected to L2 + fixed the double fee bug
- helpline icon added to fee again
- transaction hash will be shortened now if the screen width is less than 1920px
- wallet page "Token", "NFT" is not only visible when logged in

**Additional:**
Changed the wording from "connecting" and "disconnect" to "connected" and "disconnected" because that makes more sense
_(Will open a [TBD] issue if this text is needed as it has no additional value to the user as well is never used anywhere else)_

2023-03-01 18:12 UTC, sk-enya approved these changes
Looks good!

2023-03-01 18:15 UTC, merged