Bundler SDK - NPM release pipeline
bobanetwork/boba_legacy pull request #749
Opened 2023-04-27 15:28 UTC by wsdt

## Overview

Add CI/CD pipeline for `@bobanetwork/bundler_sdk`. 

resolves #[739](https://github.com/bobanetwork/boba/issues/739)

## Changes

- Rename bundler_sdk scope from `@boba` to `@bobanetwork` as the scope on npmjs is unfortunately already taken & refactored usages (but didn't do so for other packages yet - TBD)
- NPM package released once we create a new release automatically

## Testing

Test run of pipeline successful. Test package has been deleted from the registry.

2023-04-28 06:03 UTC, souradeep-das approved these changes
🚀

2023-05-04 10:37 UTC, InoMurko requested changes

2023-05-04 10:37 UTC, InoMurko commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
this probably takes `"version": "0.2.3",` from the package.json, right?
is there a way to prevent overwriting packages in NPM?

something like this: https://github.com/ethereum-optimism/optimism/pull/5413#issuecomment-1503778609

<img width="767" alt="image" src="https://user-images.githubusercontent.com/2582555/236180849-54f61578-eb05-42a6-b023-1f91fe7acd1d.png">

2023-05-04 11:49 UTC, wsdt commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
with the current configuration we only create a new package on new "Github release", not on new commit to a specific branch. So yes, right now we would need to update the version number of package.json. 

If you keep the same version number in the package.json then the release simply fails, and is not released. Basically npmjs.org prevents you from overwriting existing packages. 

@InoMurko

2023-05-05 11:50 UTC, InoMurko commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
okay, makes sense. thats good to know.

should we address the second part of my comment separately - the automation (changeset PRs)?

2023-05-05 11:53 UTC, wsdt commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
let's do it in a separate issue / PR because I guess we also might need to add a version check to avoid failing releases if possible (or auto-incrementing the version number etc).

2023-05-05 11:53 UTC, wsdt commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
let's do it in a separate issue / PR because I guess we also might need to add a version check to avoid failing releases if possible (or auto-incrementing the version number etc).

2023-05-05 11:55 UTC, wsdt commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
if we do auto-increment for the version, then we maybe could also consider releasing on commit (with changeset) as in your screenshot above.

2023-05-05 12:06 UTC, InoMurko commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
yeah, one by one! open an issue pls!

2023-05-05 12:15 UTC, wsdt commented on .github/workflows/aa-bundler-sdk.yml
> +          NODE_AUTH_TOKEN: ${{ secrets.NPM_BOBA_FOUNDATION }}
https://github.com/bobanetwork/boba/issues/780

2023-05-05 12:17 UTC, InoMurko commented
Please clean the commit history

2023-05-05 12:23 UTC, InoMurko approved these changes

2023-05-05 12:59 UTC, merged