[AA] Fix Bundler SDK commenter
bobanetwork/boba_legacy pull request #796
Opened 2023-05-10 14:29 UTC by wsdt

## Overview

PR commenter currently comments on every PR. 

## Changes

- Adding path filter

## Testing

Test PRs

2023-05-10 16:28 UTC, InoMurko commented on .github/workflows/aa-bundler-sdk-pr.yml
> +            - 'packages/boba/bundler_sdk/**/*'
and bundler_utils?

2023-05-10 16:29 UTC, InoMurko requested changes
and bundler_utils?

2023-05-10 16:29 UTC, InoMurko commented on .github/workflows/aa-bundler-sdk-pr.yml
> +        filters: |
what if changes are in bundler_utils (a dependency to bundler_sdk)?

2023-05-11 11:12 UTC, wsdt commented on .github/workflows/aa-bundler-sdk-pr.yml
> +        filters: |
shouldn't we add account_abstraction then as well?

2023-05-11 12:55 UTC, InoMurko commented on .github/workflows/aa-bundler-sdk-pr.yml
> +        filters: |
not really, because the SDK only ships code from bundler_sdk and bundler_utils - as a package.
if AA changes, and tests continue working, it means the interface between AA and the SDK didn't change hence a new version is not needed.

2023-05-11 12:55 UTC, InoMurko approved these changes
lgtm

2023-05-11 14:05 UTC, Boyuan-Chen approved these changes

2023-05-11 14:06 UTC, merged