[DRAFT] Switch from file-based db to postgresql with DB migrations
bobanetwork/boba_legacy pull request #822
Opened 2023-05-15 16:39 UTC by wsdt

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Switch from file-based db to postgresql in Teleporter and support db migrations. 

## Changes

Describe your changes and implementation choices. More details make PRs easier to review.

- Adding teleportation_db to docker-compose-side.yml
- Adding corresponding .env variables
- Modification of interfaces, etc.
- typeorm integration

## Testing

Project build & tests ran.

2023-05-15 16:39 UTC, wsdt commented
4 tests failing, rest succeeding

2023-05-24 15:43 UTC, wsdt commented
Check before merging: 
https://github.com/bobanetwork/boba/issues/846

2023-05-25 17:02 UTC, wsdt commented
Tests succeeding, will now have a look at https://github.com/bobanetwork/boba/issues/846

DO NOT MERGE YET

2023-05-25 18:04 UTC, wsdt commented
fixing coverage

2023-05-26 13:42 UTC, InoMurko approved these changes
lgtm - 

I think the only thing that *needs* fixing is 
```
describe.only('teleportation', () => {
```
not sure if the whole test gets executed with this only

2023-05-26 13:42 UTC, InoMurko commented on integration-tests/test/eth-l2/teleportation.spec.ts
> +describe.only('teleportation', () => {
what does this only do?

2023-05-26 13:42 UTC, InoMurko commented on packages/boba/teleportation/package.json
> +   "description": "The teleportation between L2s",
```suggestion
   "description": "The teleportation between L2s and L1s",
```

2023-05-26 13:42 UTC, InoMurko commented on packages/boba/teleportation/.env.example
> +POSTGRES_USER=postgres
this is a nice to have, but this reminds me of prefixing env vars for where they belong:
```
TELEPORTATION_POSTGRES_PASSWORD=abcdef
TELEPORTATION_POSTGRES_DB_HOST=teleportation_db
TELEPORTATION_POSTGRES_DB=postgres
TELEPORTATION_POSTGRES_PORT=5432
TELEPORTATION_POSTGRES_USER=postgres
TELEPORTATION_POLLING_INTERVAL=
TELEPORTATION_BLOCK_RANGE_PER_POLLING=
```
sometimes env vars get mixed or all secrets end up in one bucket and then they collide

2023-05-26 13:47 UTC, wsdt commented on integration-tests/test/eth-l2/teleportation.spec.ts
> +describe.only('teleportation', () => {
The PR is not ready to merge, the last thing missing is to get the new integration test talking to the postgres db.

2023-05-26 13:49 UTC, wsdt commented on packages/boba/teleportation/.env.example
> +POSTGRES_USER=postgres
sure will do!

2023-05-26 13:51 UTC, InoMurko commented on integration-tests/test/eth-l2/teleportation.spec.ts
> +describe.only('teleportation', () => {
ah ok! I will then turn the PR into draft again and remove the reviewers as we get emails and notifications for commits

2023-05-26 14:00 UTC, wsdt commented on integration-tests/test/eth-l2/teleportation.spec.ts
> +describe.only('teleportation', () => {
thx!

2023-05-30 14:28 UTC, wsdt commented
Integration tests seem to & should pass now

2023-06-01 11:11 UTC, wsdt commented on integration-tests/test/eth-l2/teleportation.spec.ts
now separate added as chain specific configs are otherwise not taken and despite the correct command in the dockerfile CircleCI seems to just execute the tests on boba eth. 

Sticking to what we have been doing for other tests too.

2023-06-01 11:34 UTC, wsdt commented on integration-tests/test/eth-l2/erc1155_bridge.spec.ts
> +      ).setApprovalForAll(L1Bridge.address, true, { gasLimit: 1000000 })
failing test (only fails on boba eth), comparing alt test showed manual gas limit should fix the test

2023-06-01 11:50 UTC, InoMurko requested changes

2023-06-01 11:50 UTC, InoMurko commented on .github/workflows/ts-packages.yml
> +        run: npx depcheck --ignores @types/node
there's ```.depcheckrc``` for this

2023-06-01 11:50 UTC, InoMurko commented on integration-tests/test/alt-l2/teleportation.spec.ts
> +  describe('database connection', () => {
this is not an integration test but a unit test.

2023-06-01 11:51 UTC, wsdt commented on integration-tests/test/alt-l2/teleportation.spec.ts
> +  describe('database connection', () => {
database connection? How is that supposed to be a unit test? 
I added these tests specifically to see if there is an actual connection

2023-06-01 11:58 UTC, InoMurko requested changes

2023-06-01 11:58 UTC, InoMurko commented on integration-tests/test/eth-l2/erc1155_bridge.spec.ts
> +    it('should be able to deposit token to another wallet on L2 (2)', async () => {
what exactly is the purpose of this test compared to the one ```
should be able to deposit token to another wallet on L2 (1)
```
?

2023-06-01 12:02 UTC, wsdt commented on integration-tests/test/eth-l2/erc1155_bridge.spec.ts
> +    it('should be able to deposit token to another wallet on L2 (2)', async () => {
not sure, because I didn't write them. 

Since our tests depend on each other, i assume these are there to ensure that the state from previous tests is correct and the deposit for those two different wallets work (maybe different roles/privileges)

2023-06-01 12:06 UTC, InoMurko commented on integration-tests/test/alt-l2/teleportation.spec.ts
> +  describe('database connection', () => {
the reason for this being a bad integration test is that you don't have an outside view of the application, but an inside view of the application.
so, you're using internal data structures to test whether postgres is consuming your data.

an integration test would be possible if:
teleportation as a service would expose an API that allows you to query the latest deposit.
you make a deposit, via geth and solidity, check if teleportation matches your assumption about the deposit.
in your case, you actually brought DB schema to the integraiton test that's on the parent monorepo.
I think this is too much coupling.

also, like - wouldn't other tests already cover whether you have a connection or not? if you make several deposits one after another - if blocks are not in DB - how would the application proceed to recognise new deposits for a chainid?

2023-06-01 12:08 UTC, InoMurko commented on integration-tests/test/eth-l2/erc1155_bridge.spec.ts
> +    it('should be able to deposit token to another wallet on L2 (2)', async () => {
please take a look then.
also tests should be decoupled, if they're coupled make an issue so that they get fixed.

2023-06-01 12:09 UTC, wsdt commented on integration-tests/test/alt-l2/teleportation.spec.ts
> +  describe('database connection', () => {
yes other tests would fail, tbh I added them because I they helped me discovering a typing issue with the db. 
But will remove!

2023-06-01 12:19 UTC, InoMurko approved these changes

2023-06-01 12:20 UTC, wsdt commented on integration-tests/test/eth-l2/erc1155_bridge.spec.ts
> +    it('should be able to deposit token to another wallet on L2 (2)', async () => {
the 2nd test is about depositing from another wallet (that's why we call `connect()` and have to call approve before. 
So yes it actually makes sense to have both. 

Especially since the 2nd still fails only on Boba eth for some reason. 

And yes, one needs to execute the whole describe for the tests to succeed as they depend on each other in general

2023-06-08 09:16 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
>    }
this try - catch seems weird.
imo a try catch is such an obscure part of any language, way too much usage.
```
const saved = await historyDataRepository.save(historyData)
if saved === false {
  this.logger.error(`Failed to put depositInfo! - ${error}`)
}
```

what can actually fail in this block of code? creating the object or saving into the DB?


```
try {
      lastBlock = await this._getDepositInfo(chainId)
    } catch (e) {
      this.logger.warn(`No deposit info found in chainId - ${chainId}`)
      lastBlock = depositTeleportation.height
      // store the new deposit info
      await this._putDepositInfo(chainId, lastBlock)
    }
```

this one too. try catch is for **exception** handling, not normal code branches.
I know you didn't write this, just laying it out there for future reference. don't use try catch or minimise it's usage

2023-06-08 09:44 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
>    }
My comment is wrong is the DB insertion actually throws exceptions. But then we don't need two wrapped try catches either... :-)

2023-06-08 11:00 UTC, wsdt commented on packages/boba/teleportation/src/service.ts
>    }
> this try - catch seems weird. imo a try catch is such an obscure part of any language, way too much usage.
> 
> ```
> const saved = await historyDataRepository.save(historyData)
> if saved === false {
>   this.logger.error(`Failed to put depositInfo! - ${error}`)
> }
> ```
> 
> what can actually fail in this block of code? creating the object or saving into the DB?
> 
> ```
> try {
>       lastBlock = await this._getDepositInfo(chainId)
>     } catch (e) {
>       this.logger.warn(`No deposit info found in chainId - ${chainId}`)
>       lastBlock = depositTeleportation.height
>       // store the new deposit info
>       await this._putDepositInfo(chainId, lastBlock)
>     }
> ```
> 
> this one too. try catch is for **exception** handling, not normal code branches. I know you didn't write this, just laying it out there for future reference. don't use try catch or minimise it's usage

Just replicated the prior code to not move away from current behavior. 
But happy to adapt it!

2023-06-12 18:05 UTC, wsdt commented
There is one seemingly unrelated integration test named `should be able to deposit token to another wallet on L2 (2)` that seems to fail deterministically: 
https://app.circleci.com/pipelines/github/bobanetwork/boba/3371/workflows/1bbf7589-6edc-452b-b26c-a2753e3756f5/jobs/13339


Although, locally when executing the test file all tests including the one above explicitly run through successfully, the same applies when only executing the inner describe - all tests including the one above runs through. 

BNB and AVAX tests run through too - the same test (1:1 code) runs through on Alt-L2 while failing on Boba Eth. 

It seems like that completely unrelated integration tests in other integration test files make that single test fail. 

As all teleporter integration tests run through successfully, as so do other integration tests - I suggest that we look at our integration tests separately as it really looks like that we should have a look at the dependencies between our integration tests. 

Feels a bit out of scope for this and I depend on this code for continuing with: 
https://github.com/bobanetwork/boba/issues/795

@InoMurko @souradeep-das please let me know what you think.

2023-06-12 18:06 UTC, wsdt commented
Created an issue: 
https://github.com/bobanetwork/boba/issues/953

2023-06-14 10:40 UTC, InoMurko commented on packages/boba/teleportation/src/service.ts
>    }
You changed the underlying database storage. You should change the current behaviour, especially if it's wrong and/or harmful.

2023-06-14 10:42 UTC, InoMurko commented
```
There is one seemingly unrelated integration test named should be able to deposit token to another wallet on L2 (2) that seems to fail deterministically:
```
deterministically or probalisticly?

2023-06-14 10:43 UTC, InoMurko approved these changes
lets see how flaky things get in the main repo

2023-06-16 10:42 UTC, souradeep-das commented
yeah its weird, sometimes we have seen it is because of the GasOracle not being able to estimateGas precisely and that fails the tests. Passing an explicit { gasLimit: 7000000 } to the transaction mostly makes it back to working. (but not sure in this case)

2023-06-16 11:00 UTC, souradeep-das approved these changes
looks great to me!

2023-06-19 17:09 UTC, wsdt commented
Gateway dependencies broke the project/got into conflict with the added dependencies in this PR. 
Works now again

2023-06-19 20:25 UTC, merged