Feat/move reducers to TS
bobanetwork/boba_legacy pull request #832
Opened 2023-05-17 13:18 UTC by alvaro-ricotta

Reducers have been updated to TypeScript.
We implemented simple typings to better understand what type of data we expect in each reducer. Additionally, we changed the previous reducer's switch case-based approach to a config-driven version.

Finally, we modified the methods to select the handler based on the previously established config-driven approach.

2023-05-17 13:35 UTC, InoMurko commented on packages/boba/gateway/src/reducers/loginReducer.ts
> +  along with this program. If not, see <https://www.gnu.org/licenses/>.
eh?? :D

2023-05-17 13:36 UTC, InoMurko commented on packages/boba/gateway/src/reducers/notificationReducer.ts
> +*/
```suggestion

```

2023-05-17 14:06 UTC, alvaro-ricotta commented
All disclaimer has been updated @InoMurko

2023-05-22 06:29 UTC, sk-enya requested changes
As this pr is completely for reducer can you please migrate the `reducers/index.js` file to typescript with required types?

2023-05-22 06:29 UTC, sk-enya commented on packages/boba/gateway/src/reducers/loginReducer.ts
We are not using the LoginReducer in application, please remove this!

2023-05-22 06:29 UTC, sk-enya commented on packages/boba/gateway/src/reducers/notificationReducer.ts
> +export default notificationReducer
This block code seems repeated, so can we move it to separate file and reuse where it's needed!

2023-05-22 06:29 UTC, sk-enya commented on packages/boba/gateway/src/reducers/signatureReducer.ts
> +type ActionTypes = 'EXIT/LP/SIGNED' | 'EXIT/TRAD/SIGNED' | 'DEPOSIT/LP/SIGNED'
Please move the constants to separate file or variable at top.
like 
```
const EXIT_LP_SIGNED = 'EXIT/LP/SIGNED'

/// refer the same for defining the types and actions types in reducere also let's use the same in selectors too.
```

2023-05-22 06:29 UTC, sk-enya commented on packages/boba/gateway/src/reducers/transactionReducer.ts
> +  | 'CDM/COMPLETE/RESET'
Like mention above, define constant var and use it across app.

2023-05-22 06:29 UTC, sk-enya commented on packages/boba/gateway/src/reducers/transactionReducer.ts
> +  {
Listener for the below actions in reducer is missing.

```
SETTLE_v0/CREATE/SUCCESS'
  | 'SETTLE_v1/CREATE/SUCCESS'
  | 'SETTLE_v2/CREATE/SUCCESS'
  | 'SETTLE_v2OLO/CREATE/SUCCESS'
  | 'SETTLE_v3/CREATE/SUCCESS'
  | 'SETTLE_v3OLO/CREATE/SUCCESS'

```

2023-07-03 19:55 UTC, InoMurko commented
Reopen if fixed.

2023-07-03 19:55 UTC, closed without merging