[DRAFT] Add Snyk, Dependabot, Secretfinder
bobanetwork/boba_legacy pull request #838
Opened 2023-05-18 12:50 UTC by wsdt

:clipboard: Resolves #788

## Overview

Add Snyk, Dependabot, Secretfinder

## Changes

- Add Dependabot
- Add Snyk [ToDo]
- Add SecretFinder [ToDo]

## Testing

workflows tested via PRs

2023-05-18 14:51 UTC, wsdt commented on ops/docker/Dockerfile.monitor
> +FROM --platform=linux/amd64 node:20.1-buster
these version bumps are just 4 highly critical issues. 

If we want these in separate PRs kindly let me know

2023-05-19 08:05 UTC, souradeep-das commented on .github/workflows/snyk.yml
> +on: push
do we want branch filters?

2023-05-19 13:48 UTC, wsdt commented on .github/workflows/snyk.yml
> +on: push
sure! done

2023-05-19 14:33 UTC, souradeep-das approved these changes
lgtm!

2023-05-19 14:33 UTC, souradeep-das commented on .github/workflows/secret-detect.yml
> +  pull_request:
just noticed sorry, is ref filtering needed here too? (to avoid running for docs-in-monorepo etc)

2023-05-22 13:33 UTC, wsdt commented on .github/workflows/secret-detect.yml
> +  pull_request:
will add, but thought it would be relevant for docs-in-monrepo too. :-)

2023-05-24 12:22 UTC, InoMurko requested changes

2023-05-24 12:22 UTC, InoMurko commented on .github/dependabot.yml
> +      interval: "weekly"
```suggestion
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
     reviewers:
      - "souradeep-das"
      - "wsdt"
      - "Boyuan-Chen"
      - "InoMurko"
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/ops" # Location of package manifests
    schedule:
      interval: "weekly"
     reviewers:
      - "souradeep-das"
      - "wsdt"
      - "Boyuan-Chen"
      - "InoMurko"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "souradeep-das"
      - "wsdt"
      - "Boyuan-Chen"
      - "InoMurko"
```

2023-05-26 15:56 UTC, InoMurko approved these changes

2023-05-26 15:59 UTC, merged