fix: bundler relies on eth_getLogs with indefinite range
bobanetwork/boba_legacy pull request #855
Opened 2023-05-26 19:22 UTC by souradeep-das

:clipboard: https://github.com/bobanetwork/boba/issues/843

## Overview

Fixes bundler reliance on eth_getLogs with range > 5000

## Changes

- bundler splits eth_getLogs requests if the range to request is > 5k
- a new config 'l1Offset' has been added to bundler, to allow the bundler to start watching from a specific block
- adds opts {fromBlock and toBlock} for eth_getUserOperationReceipt and eth_getUserOperationByHash

## Testing

circleci logs

2023-05-26 19:23 UTC, souradeep-das commented on packages/boba/bundler/src/modules/EventsManager.ts
> +          startBlock+4999
assuming fromBlock and toBlock in eth_getLogs range is inclusive

2023-05-30 11:27 UTC, InoMurko requested changes

2023-05-30 11:27 UTC, InoMurko commented on packages/boba/bundler/src/BundlerServer.ts
> +        result = await this.methodHandler.getUserOperationByHash(params[0], params[1])
is there a specification attached to eip-4337 and is this breaking it?

2023-05-30 11:27 UTC, InoMurko commented on packages/boba/bundler/src/modules/EventsManager.ts
> +          startBlock+4999
should we extract away the 4999? could be less, could be more!

2023-05-31 10:58 UTC, souradeep-das commented on packages/boba/bundler/src/BundlerServer.ts
> +        result = await this.methodHandler.getUserOperationByHash(params[0], params[1])
hmmm right, the original specs specify one parameter. 
The second parameter here is optional though, but do we want to stick with one param and split into multiple requests?

2023-05-31 11:00 UTC, wsdt commented on packages/boba/bundler/src/BundlerServer.ts
> +        result = await this.methodHandler.getUserOperationByHash(params[0], params[1])
if we go with multiple request we could think about `Promise.all`

2023-05-31 11:39 UTC, InoMurko commented on packages/boba/bundler/src/BundlerServer.ts
> +        result = await this.methodHandler.getUserOperationByHash(params[0], params[1])
as you said @souradeep-das the additional parameters are optional so things don't break the specs.
whereas I'm now doubting the quality or usability of the specs.

the client either needs to keep track of *when* (in terms of blocks) a user operation occurred so that it supplies the optional params, or as per specs, scan ALL blocks, not all providers allow you to do that.

@souradeep-das would this chunk of code scan all logs from the deployment of `entryPoint` till `latest` block?
```
const event = await this.entryPoint.queryFilter(
      this.entryPoint.filters.UserOperationEvent(userOpHash)
    )
```

2023-05-31 15:10 UTC, souradeep-das commented on packages/boba/bundler/src/BundlerServer.ts
> +        result = await this.methodHandler.getUserOperationByHash(params[0], params[1])
yes this would look for the exact event (with the above filter) from the start of the chain until the latest block. Since the response will consist only of one event, some L1 providers eth_getLogs would work because they sometimes only have a limit on the response size. For boba, however this would fail because it wants a block range. 

Hmm true, I was trying to delegate the task of specifying the range to the user, since the bundler does not directly use this, but valid point - the user might not be aware. But otherwise, if we split and do the searching on the bundler, that might be multiple requests for each user request. does that open any DoS angle? maybe more with Promise.all?

2023-05-31 15:57 UTC, souradeep-das commented on packages/boba/bundler/src/modules/EventsManager.ts
> +    readonly l1Offset: number
woops I'll change this to l2Offset and make "5000" configurable

2023-05-31 16:14 UTC, souradeep-das commented on packages/boba/bundler/src/BundlerServer.ts
> +        result = await this.methodHandler.getUserOperationByHash(params[0], params[1])
as per our discussions, created an issue for this here: https://github.com/bobanetwork/boba/issues/865, which I will tackle later. Thanks for pointing this out guys!

2023-05-31 16:24 UTC, InoMurko commented on packages/boba/bundler/src/modules/EventsManager.ts
> +          startBlock+4999
https://github.com/bobanetwork/boba/issues/866

2023-05-31 16:24 UTC, InoMurko approved these changes

2023-05-31 17:41 UTC, souradeep-das commented
converted the log chunksize to a configurable value, please review the last two commits. (associated docs updated here https://github.com/bobanetwork/boba/pull/867)

2023-06-01 11:17 UTC, wsdt commented on packages/boba/bundler/src/UserOpMethodHandler.ts
> +    opts?: any
Should we add a type for this?

2023-06-01 11:18 UTC, wsdt approved these changes
left a comment, looks good

2023-06-01 11:18 UTC, merged