Teleporter routes
bobanetwork/boba_legacy pull request #959
Opened 2023-06-15 18:14 UTC by wsdt

:clipboard: Resolves https://github.com/bobanetwork/boba/issues/795

## Overview

Allow flexible ERC20 / native Asset routes. 

## Changes

- Smart contract changes to support ERC20 and Native assets generically
- Teleporter service adapted & refactored
- General refactoring
- Added tests

## Testing

All e2e & unit tests run through.

2023-06-26 17:21 UTC, wsdt commented
- Integration & unit tests succeed
- Testnet tests succeeded, some examples tested: 
--> BOBA as native from AVAX to BOBA as native on BNB: 
- Deposit on Avax: 
https://blockexplorer.testnet.avax.boba.network/tx/0x5839ec74eded66e91f78ba12c2b80c7e8cf308b0df9a2e5761f6baa6163380da
- Disbursement on BNB: 
https://blockexplorer.testnet.bnb.boba.network/tx/0xf006b61644fb63c7ba2577fc8ab4827f8054424becee2a54d8b8e7dfdcbaa112


--> BOBA as native from BNB to BOBA as token on Goerli: 
- Deposit on BNB: 
https://blockexplorer.testnet.bnb.boba.network/tx/0xe6b6e57d8b174dec2d358867218b28dc7c92aefaa7553274f4565817ebdb944f
- Disbursement on Goerli: https://testnet.bobascan.com/tx/0x30ec6a8220db798c6f6d2fa8ad604dce6cfb50c242ae59941cdc5a30e3f5c92e

2023-06-27 15:04 UTC, wsdt commented
@InoMurko ready for audits once merged imho

2023-06-28 12:44 UTC, InoMurko approved these changes
Lots of work went into this, good stuff!

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +        uint256 transferTimestampCheckPoint;
```suggestion
        bool supported;
        // The minimum amount that needs to be deposited in a receive.
        uint256 minDepositAmount;
        // The maximum amount that can be deposited in a receive.
        uint256 maxDepositAmount;
        // set maximum amount of tokens that can be transferred in 24 hours
        uint256 maxTransferAmountPerDay;
        // The total amount of tokens transferred in 24 hours
        uint256 transferredAmount;
        // The timestamp of the checkpoint
        uint256 transferTimestampCheckPoint;
```

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +    * @dev Add support of a specific token on this network.
```suggestion
    * @dev Add support of a specific ERC20 token on this network.
```

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +        // doesn't ensure it's ERC20
does it make sense to do supportsInterface for erc20 check here?

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +        // set maximum amount of tokens can be transferred in 24 hours
```suggestion
        // set maximum amount of tokens that can be transferred in 24 hours
```

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(supportedTokens[_token].supported == false, "Already supported");
would this ever be false? since when you're removing support you're not actually setting it to false, but 
```
delete supportedTokens[_token];
```

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/test/endToEndTests/teleportation.spec.ts
> +      expect(supToken[2]).to.eq('0')
it seems that if I remove this test, others start failing. can we ensure tests are decoupled?

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/contracts/test/endToEndTests/teleportation.spec.ts
> +    it('should not disburse BOBA tokens if any disbursement is native/zero address', async () => {
should BOBA in this case be replaced with ERC20? So that we don't confuse this isn't BOBA specific

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/teleportation/README.md
> +- Proxy__Teleportation deployed to: `0x2965Cc3d8Ba6790d6fCCedaC44864f2ff6e01f21`
```suggestion
### Boba Opera Testnet (Fantom)
- Teleportation deployed to: `0x5ACFD6c90015dd5241BeBCE9Cec93D2D01f10580`
- Proxy__Teleportation deployed to: `0x2965Cc3d8Ba6790d6fCCedaC44864f2ff6e01f21`
```

these should be removed

2023-06-28 12:44 UTC, InoMurko commented on packages/boba/teleportation/src/exec/run.ts
> +    })
nice!

2023-06-28 16:26 UTC, wsdt commented on packages/boba/contracts/test/endToEndTests/teleportation.spec.ts
> +      expect(supToken[2]).to.eq('0')
sure fixed locally!

2023-06-28 17:48 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +        // doesn't ensure it's ERC20
added, but minor note: had to adapt our L1ERC20.sol - please verify. 
Just added the supportsInterface method 

Need to check if our BOBA token actually implements it, otherwise we can't add this check. 

In our Teleporter tests we use L1ERC20, I just kept it that way.

2023-06-28 17:49 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +        // doesn't ensure it's ERC20
this might be @souradeep-das domain. He’s seen it all

2023-06-29 18:48 UTC, souradeep-das reviewed
mainly thinking about these two things a) non-relation between supportedToken and chainId b) erc20 erc165 checker, added some comments, otherwise looks good!!

2023-06-29 18:48 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        uint256 maxTransferAmountPerDay = 100_000e18;
this amount might be very high for eth networks (ETH native) (or low depending on the network), can we pass this as an arg?

2023-06-29 18:48 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) == _token || _token.supportsInterface(type(IERC20).interfaceId), "Not ERC20 or native");
Theres one thing though - that this might not work for the L1 deployments of this contract, since L1 ERC20s don't inherit ERC165,
if teleportation is supposed to work for L1<>L2,

2023-06-29 18:48 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) != _token || _amount == msg.value, "Native amount invalid");
minor: auditors might point that any msg.value supplied is wasted when token is not native token but imo thats ok (your call)

2023-06-29 18:48 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        address token,
minor: do we want to add the token to the 'DisbursementSuccess' event too?

2023-06-29 18:48 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
with opening this method for all tokens, is there a re-entrancy?

2023-06-29 18:48 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +    function addSupportedToken(address _token, uint256 _minDepositAmount, uint256 _maxDepositAmount, uint256 _maxTransferAmountPerDay) public onlyOwner() onlyInitialized() {
Thinking about this, I think there could be a fundamental concern with the non-relation of supportedToken and supportedChain? For ex- If there are teleportation contracts TP1, TP2, TP3 on three different chains. TP1 has supportedChainId set to true for chainIds of TP2 and TP3. Now if TP1 supports a token TK to enable its movement between TP1 and TP3. (But the token TK is not available on TP2 chain). A user could still deposit (teleport) TK on TP1 referencing the TP2 chain as _toChain. I think [token][toChainId] should be the map to identify support? Am I thinking about this correctly?

2023-06-30 10:30 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) == _token || _token.supportsInterface(type(IERC20).interfaceId), "Not ERC20 or native");
reverted back to isContract check thx!

2023-06-30 10:43 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +            IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
- All tokens are whitelisted by us. Only the ZeroAddress for indicating native assets is added by default.
- Other safeTransfer(From) calls are within the onlyOwner modifier, so only to be called by us. 
- for `teleportAsset()`: even tough tokens are added via whitelisting, one shouldn't be able to conduct re-entrancy (and even if somehow possible at least limit it) as 

1. `transferTimestampCheckPoint` is updated before the transfer and would let the reentrancy fail.
2. Further limiting it: `supToken.transferredAmount` will be checked against maxTransferAmountPerDay before doing the transfer.

Happy for feedback

2023-06-30 11:34 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +            IERC20(_token).safeTransferFrom(msg.sender, address(this), _amount);
makes sense!

2023-06-30 12:22 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) != _token || _amount == msg.value, "Native amount invalid");
added check thx!

2023-06-30 20:05 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +    function addSupportedToken(address _token, uint256 _minDepositAmount, uint256 _maxDepositAmount, uint256 _maxTransferAmountPerDay) public onlyOwner() onlyInitialized() {
done! good catch - BUT: we have to keep in mind that this exponentially increases the amount of paths we need to track and configure.

2023-07-03 12:51 UTC, InoMurko requested changes

2023-07-03 12:51 UTC, InoMurko commented on packages/boba/contracts/contracts/Teleportation.sol
> +contract Teleportation is PausableUpgradeable, MulticallUpgradeable {
I think at this point we're missing an extended definition of the contracts purpose and mechanics in a comment so that auditors have a better understanding of it's purpose.
The shoutout to optimism is at this point more or less irrelevant,I don't think much of it is still there (the links also don't work anymore).

2023-07-03 15:58 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +contract Teleportation is PausableUpgradeable, MulticallUpgradeable {
sure!

2023-07-03 19:49 UTC, InoMurko approved these changes

2023-07-03 19:53 UTC, Boyuan-Chen approved these changes
Could you please remove Bobabeam and Bobaopera from the `chains.ts`?

2023-07-04 11:18 UTC, merged

2023-07-05 06:30 UTC, souradeep-das commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) != _token || (address(0) == _token && _amount == msg.value), "Native amount invalid");
since the extra msg.value is an issue only when token!=addr(0), and there is the OR in between, maybe this extra check might not block msg.value?

2023-07-05 08:06 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) != _token || (address(0) == _token && _amount == msg.value), "Native amount invalid");
thx! https://github.com/bobanetwork/boba/pull/1008

2023-07-05 08:06 UTC, wsdt commented on packages/boba/contracts/contracts/Teleportation.sol
> +        require(address(0) != _token || (address(0) == _token && _amount == msg.value), "Native amount invalid");
thx! https://github.com/bobanetwork/boba/pull/1008