Feat/background page title plus
bobanetwork/boba_legacy pull request #981
Opened 2023-06-21 14:45 UTC by alvaro-ricotta

:clipboard: Add associated issues, tickets, docs URL here.

## Overview

Background component has been added
PageTitle component has been added

## Changes

We added two new components:

Background component: It handles the gradient and a small animation of lines.
PageTitle component: It displays global titles on each necessary page.
PageTitle was developed using TypeScript (ts), Jest, and Storybook, so it includes testing and documentation capabilities. In the case of Background, it is a simple styled component and doesn't require these additional tools.

We added a **hard reset** in the global style of the theme to avoid design inconsistencies and issues across different browsers.

The Header component was updated to include a fixed background in both themes.

2023-06-21 16:06 UTC, sk-enya commented
Review comments:
1. Looks background design is not matching with designs
2. Looks background checks layout seems to be rolling down countinously like an animation!

2023-06-21 16:09 UTC, sk-enya commented on packages/boba/gateway/src/components/global/background/styles.ts
> +const playAnimation = keyframes`
Is it mentioned somewhere to have animation?

2023-06-21 22:41 UTC, sk-enya commented on packages/boba/gateway/src/components/global/PageTitle/index.tsx
> +  const { title: pageTitle, slug: pageSlug } =
This is fine as far as we have pages related title and slug.

But let's consider in case of bridge page we don't have this so doesn't make sense to render the compoenent with empty data. 

let's return the null or just <></> if no path matches with config.

2023-06-21 22:44 UTC, sk-enya requested changes

2023-06-21 22:44 UTC, sk-enya commented on packages/boba/gateway/src/components/layout/PageTitle/index.tsx
> +}
This is fine as far as we have pages related title and slug.

But let's consider in case of bridge page we don't have this so doesn't make sense to render the compoenent with empty data.

let's return the null or just <></> if no path matches with config.

2023-06-21 22:45 UTC, sk-enya commented
@alvaro-ricotta I haven't found any changes for the background for bridge & other pages. 
can you please fix those as well?

2023-06-21 23:03 UTC, alvaro-ricotta commented on packages/boba/gateway/src/components/layout/PageTitle/index.tsx
> +}
MMM, it's a PageTitle right? There should be a path/title available there.

2023-06-22 15:55 UTC, alvaro-ricotta commented
> @alvaro-ricotta I haven't found any changes for the background for bridge & other pages. can you please fix those as well?

I just pushed the update for this requeriment

2023-06-22 17:28 UTC, merged